#include "Engine/Runtime/Components/EnvironmentComponent.hpp"

#include "Engine/Runtime/Reflection/PropertyMeta.hpp"

#include <entt/meta/factory.hpp>

namespace Runtime
{
    void EnvironmentComponent::RegisterReflection()
    {
        using namespace entt::literals;
        using namespace Reflection;

        entt::meta_factory<EnvironmentComponent>()
            .type("EnvironmentComponent"_hs)
            .data<&EnvironmentComponent::SetHasSky, &EnvironmentComponent::GetHasSky>("HasSky")
                .custom<PropertyMeta>(PropertyPresets::Editable("Has Sky", "Environment", "Enable HDR sky lighting"))
            .data<&EnvironmentComponent::SetSkyIdx, &EnvironmentComponent::GetSkyIdx>("SkyIdx")
                .custom<PropertyMeta>(PropertyPresets::Editable("Sky Index", "Environment", "HDR sky texture index"))
            .data<&EnvironmentComponent::SetSkyRotation, &EnvironmentComponent::GetSkyRotation>("SkyRotation")
                .custom<PropertyMeta>(PropertyPresets::Editable("Sky Rotation", "Environment", "Horizontal sky rotation"))
            .data<&EnvironmentComponent::SetSkyIntensity, &EnvironmentComponent::GetSkyIntensity>("SkyIntensity")
                .custom<PropertyMeta>(PropertyPresets::Editable("Sky Intensity", "Environment", "Sky lighting intensity"))
            .data<&EnvironmentComponent::SetSkyColor, &EnvironmentComponent::GetSkyColor>("SkyColor")
                .custom<PropertyMeta>(PropertyPresets::Editable("Sky Color", "Environment", "Sky lighting tint"))
            .data<&EnvironmentComponent::SetHasSun, &EnvironmentComponent::GetHasSun>("HasSun")
                .custom<PropertyMeta>(PropertyPresets::Editable("Has Sun", "Environment", "Enable directional sunlight"))
            .data<&EnvironmentComponent::SetSunRotation, &EnvironmentComponent::GetSunRotation>("SunRotation")
                .custom<PropertyMeta>(PropertyPresets::Editable("Sun Rotation", "Environment", "Sun azimuth rotation"))
            .data<&EnvironmentComponent::SetSunElevation, &EnvironmentComponent::GetSunElevation>("SunElevation")
                .custom<PropertyMeta>(PropertyPresets::Editable("Sun Elevation", "Environment", "Sun elevation in radians"))
            .data<&EnvironmentComponent::SetSunIntensity, &EnvironmentComponent::GetSunIntensity>("SunIntensity")
                .custom<PropertyMeta>(PropertyPresets::Editable("Sun Intensity", "Environment", "Sun light intensity"))
            .data<&EnvironmentComponent::SetSunColor, &EnvironmentComponent::GetSunColor>("SunColor")
                .custom<PropertyMeta>(PropertyPresets::Editable("Sun Color", "Environment", "Directional sunlight color"))
            .data<&EnvironmentComponent::SetAtmosphereEnabled, &EnvironmentComponent::GetAtmosphereEnabled>("AtmosphereEnabled")
                .custom<PropertyMeta>(PropertyPresets::Editable("Enabled", "Atmosphere", "Enable the procedural atmosphere sky"))
            .data<&EnvironmentComponent::SetAerialPerspectiveEnabled, &EnvironmentComponent::GetAerialPerspectiveEnabled>("AerialPerspectiveEnabled")
                .custom<PropertyMeta>(PropertyPresets::Editable("Aerial Perspective", "Atmosphere", "Apply atmospheric aerial perspective to scene geometry"))
            .data<&EnvironmentComponent::SetHeightFogEnabled, &EnvironmentComponent::GetHeightFogEnabled>("HeightFogEnabled")
                .custom<PropertyMeta>(PropertyPresets::Editable("Enabled", "Height Fog", "Enable exponential height fog"))
            .data<&EnvironmentComponent::SetRayleighScattering, &EnvironmentComponent::GetRayleighScattering>("RayleighScattering")
                .custom<PropertyMeta>(PropertyPresets::Editable("Rayleigh Scattering", "Atmosphere", "Rayleigh scattering coefficients (1/km)"))
            .data<&EnvironmentComponent::SetRayleighDensityH, &EnvironmentComponent::GetRayleighDensityH>("RayleighDensityH")
                .custom<PropertyMeta>(PropertyPresets::Editable("Rayleigh Scale Height", "Atmosphere", "Rayleigh density scale height (km)"))
            .data<&EnvironmentComponent::SetMieScattering, &EnvironmentComponent::GetMieScattering>("MieScattering")
                .custom<PropertyMeta>(PropertyPresets::Editable("Mie Scattering", "Atmosphere", "Mie scattering coefficients (1/km)"))
            .data<&EnvironmentComponent::SetMieDensityH, &EnvironmentComponent::GetMieDensityH>("MieDensityH")
                .custom<PropertyMeta>(PropertyPresets::Editable("Mie Scale Height", "Atmosphere", "Mie density scale height (km)"))
            .data<&EnvironmentComponent::SetMieAbsorption, &EnvironmentComponent::GetMieAbsorption>("MieAbsorption")
                .custom<PropertyMeta>(PropertyPresets::Editable("Mie Absorption", "Atmosphere", "Mie absorption coefficients (1/km)"))
            .data<&EnvironmentComponent::SetMiePhaseG, &EnvironmentComponent::GetMiePhaseG>("MiePhaseG")
                .custom<PropertyMeta>(PropertyPresets::Editable("Mie Phase G", "Atmosphere", "Henyey-Greenstein anisotropy"))
            .data<&EnvironmentComponent::SetOzoneAbsorption, &EnvironmentComponent::GetOzoneAbsorption>("OzoneAbsorption")
                .custom<PropertyMeta>(PropertyPresets::Editable("Ozone Absorption", "Atmosphere", "Ozone absorption coefficients (1/km)"))
            .data<&EnvironmentComponent::SetOzoneCenterAltitude, &EnvironmentComponent::GetOzoneCenterAltitude>("OzoneCenterAltitude")
                .custom<PropertyMeta>(PropertyPresets::Editable("Ozone Center", "Atmosphere", "Ozone layer center altitude (km)"))
            .data<&EnvironmentComponent::SetOzoneWidth, &EnvironmentComponent::GetOzoneWidth>("OzoneWidth")
                .custom<PropertyMeta>(PropertyPresets::Editable("Ozone Width", "Atmosphere", "Ozone layer half width (km)"))
            .data<&EnvironmentComponent::SetGroundAlbedo, &EnvironmentComponent::GetGroundAlbedo>("GroundAlbedo")
                .custom<PropertyMeta>(PropertyPresets::Editable("Ground Albedo", "Atmosphere", "Planet ground albedo"))
            .data<&EnvironmentComponent::SetBottomRadius, &EnvironmentComponent::GetBottomRadius>("BottomRadius")
                .custom<PropertyMeta>(PropertyPresets::Editable("Bottom Radius", "Atmosphere", "Planet radius (km)"))
            .data<&EnvironmentComponent::SetTopRadius, &EnvironmentComponent::GetTopRadius>("TopRadius")
                .custom<PropertyMeta>(PropertyPresets::Editable("Top Radius", "Atmosphere", "Atmosphere top radius (km)"))
            .data<&EnvironmentComponent::SetWorldUnitsPerKm, &EnvironmentComponent::GetWorldUnitsPerKm>("WorldUnitsPerKm")
                .custom<PropertyMeta>(PropertyPresets::Editable("World Units Per Km", "Atmosphere", "World-to-kilometre conversion"))
            .data<&EnvironmentComponent::SetWorldOriginAltitude, &EnvironmentComponent::GetWorldOriginAltitude>("WorldOriginAltitude")
                .custom<PropertyMeta>(PropertyPresets::Editable("Origin Altitude", "Atmosphere", "Altitude of world y=0 (km)"))
            .data<&EnvironmentComponent::SetAerialPerspectiveMaxDistance, &EnvironmentComponent::GetAerialPerspectiveMaxDistance>("AerialPerspectiveMaxDistance")
                .custom<PropertyMeta>(PropertyPresets::Editable("AP Max Distance", "Atmosphere", "Aerial perspective range in world units"))
            .data<&EnvironmentComponent::SetSkyLuminanceScale, &EnvironmentComponent::GetSkyLuminanceScale>("SkyLuminanceScale")
                .custom<PropertyMeta>(PropertyPresets::Editable("Sky Luminance Scale", "Atmosphere", "Procedural sky luminance multiplier"))
            .data<&EnvironmentComponent::SetFogInscatteringColor, &EnvironmentComponent::GetFogInscatteringColor>("FogInscatteringColor")
                .custom<PropertyMeta>(PropertyPresets::Editable("Fog Color", "Height Fog", "Height-fog in-scattering color"))
            .data<&EnvironmentComponent::SetFogDensity, &EnvironmentComponent::GetFogDensity>("FogDensity")
                .custom<PropertyMeta>(PropertyPresets::Editable("Fog Density", "Height Fog", "Sea-level extinction density"))
            .data<&EnvironmentComponent::SetFogHeightFalloff, &EnvironmentComponent::GetFogHeightFalloff>("FogHeightFalloff")
                .custom<PropertyMeta>(PropertyPresets::Editable("Height Falloff", "Height Fog", "Exponential height falloff"))
            .data<&EnvironmentComponent::SetFogBaseHeight, &EnvironmentComponent::GetFogBaseHeight>("FogBaseHeight")
                .custom<PropertyMeta>(PropertyPresets::Editable("Base Height", "Height Fog", "Fog base height in world units"))
            .data<&EnvironmentComponent::SetFogStartDistance, &EnvironmentComponent::GetFogStartDistance>("FogStartDistance")
                .custom<PropertyMeta>(PropertyPresets::Editable("Start Distance", "Height Fog", "Distance before fog begins"))
            .data<&EnvironmentComponent::SetFogMaxOpacity, &EnvironmentComponent::GetFogMaxOpacity>("FogMaxOpacity")
                .custom<PropertyMeta>(PropertyPresets::Editable("Max Opacity", "Height Fog", "Maximum fog opacity"))
            .data<&EnvironmentComponent::SetControlSpeed, &EnvironmentComponent::GetControlSpeed>("ControlSpeed")
                .custom<PropertyMeta>(PropertyPresets::Editable("Control Speed", "Camera", "Default scene camera control speed"))
            .data<&EnvironmentComponent::SetGammaCorrection, &EnvironmentComponent::GetGammaCorrection>("GammaCorrection")
                .custom<PropertyMeta>(PropertyPresets::Editable("Gamma Correction", "Environment", "Enable gamma correction"));
    }
}
