package geo

import (
	"fmt"
	"math"
	"strings"
)

// PartScene is one part's input to the area emitter.
type PartScene struct {
	Part    Part
	Tile    Tile
	IR      *IR
	Grid    *HeightGrid
	HmapRef string
	LOD     LOD
	Edges   Edges
}

// EmitMosaic renders a grid of parts into one scene file.
//
// One file, N terrains. Each part gets its own TERR (a terrain is always
// centred on its own origin, and the cell cap is per terrain — that is the
// whole reason for tiling), its own symbols, and a module holding everything it
// owns in part-local coordinates. The assembly places each module with a
// translate. The engine already accepts this: a terrain payload records the
// transform it was instantiated under and the TerrainComponent carries a
// world-to-local matrix, so a moved terrain answers height queries correctly.
func EmitMosaic(m Mosaic, parts []PartScene, opt EmitOptions) (string, EmitReport) {
	if len(parts) == 1 {
		// A 1x1 area is a tile. Keep writing exactly the flat scene the
		// pipeline has always written, so every tile already on disk or in
		// geo.pak stays reproducible.
		p := parts[0]
		return Emit(p.Tile, p.IR, p.Grid, p.HmapRef, opt.WithLOD(p.LOD))
	}

	var report EmitReport
	var s strings.Builder

	anyDetail := false
	for _, p := range parts {
		if opt.WithLOD(p.LOD).Detail {
			anyDetail = true
		}
	}
	writeMosaicHeader(&s, m, parts, &report)
	writePreamble(&s, anyDetail)

	type placedPart struct {
		module  string
		offsetX float64
		offsetY float64
		lod     LOD
	}
	var placedParts []placedPart
	for _, p := range parts {
		sc := scope{suffix: p.Part.ID}
		partOpt := opt.WithLOD(p.LOD)
		fmt.Fprintf(&s, "// ---------------- part %s (ring %d, %s detail) at [%s, %s] ----------------\n",
			p.Part.ID, p.Part.Ring, p.LOD, fnum(p.Part.OffsetX), fnum(p.Part.OffsetY))
		calls := emitPart(&s, partInput{
			tile: p.Tile, ir: p.IR, grid: p.Grid, hmapRef: p.HmapRef,
			opt: partOpt, sc: sc, edges: p.Edges,
		}, &report)
		module := sc.sym("part")
		fmt.Fprintf(&s, "module %s()\n{\n", module)
		for _, c := range calls {
			fmt.Fprintf(&s, "    %s\n", c)
		}
		s.WriteString("}\n\n")
		report.Triangles += 2 * p.Tile.Cells * p.Tile.Cells
		placedParts = append(placedParts, placedPart{
			module: module, offsetX: p.Part.OffsetX, offsetY: p.Part.OffsetY, lod: p.LOD,
		})
	}

	s.WriteString("// ================= assembly =================\n")
	for _, p := range placedParts {
		fmt.Fprintf(&s, "translate([%s, %s, 0]) %s();\n", fnum(p.offsetX), fnum(p.offsetY), p.module)
	}
	s.WriteString("\n")
	writeMosaicCameras(&s, m, parts)
	return s.String(), report
}

func writeMosaicHeader(s *strings.Builder, m Mosaic, parts []PartScene, report *EmitReport) {
	grid := m.Grid()
	lo, hi := math.Inf(1), math.Inf(-1)
	buildings := 0
	var meta *TerrainMeta
	for _, p := range parts {
		a, b := p.Grid.Bounds()
		lo, hi = math.Min(lo, a), math.Max(hi, b)
		buildings += len(p.IR.Buildings)
		if meta == nil && p.IR.Terrain != nil {
			meta = p.IR.Terrain
		}
	}
	fmt.Fprintf(s, "// %s.scad — generated by `gnb geo`, do not edit by hand.\n//\n", m.Name)
	fmt.Fprintf(s, "// Real-world area: %.5f, %.5f — %.0f x %.0f m as a %dx%d grid of %.0f m parts,\n",
		m.Lat, m.Lon, m.SizeM, m.SizeM, grid, grid, PartSizeM)
	fmt.Fprintf(s, "// %d x %d terrain cells each (%.1f m/cell).\n",
		m.Cells, m.Cells, PartSizeM/float64(m.Cells))
	water := "no water body"
	base := 0.0
	if meta != nil {
		base = meta.BaseElevation
		if meta.HasWater {
			kind := "inland water"
			if meta.IsSea {
				kind = "sea level"
			}
			water = fmt.Sprintf("%s %.1f m", kind, meta.WaterLevel)
		}
	}
	fmt.Fprintf(s, "// Elevation %.1f .. %.1f m, datum %.1f m, %s — one plan for the whole area,\n",
		lo, hi, base, water)
	s.WriteString("// so the parts share a water plane and a colour ramp instead of stepping at\n")
	s.WriteString("// every seam.\n")
	s.WriteString("// SCAD +x east, +y north, 1 unit = 1 m; each part is placed with a translate.\n//\n")
	s.WriteString("// Data sources — attribution is required, keep this block:\n")
	for _, a := range parts[0].IR.Attribution {
		fmt.Fprintf(s, "//   %s\n", a)
	}
	fmt.Fprintf(s, "//\n// %d parts, %d OSM buildings before filtering. Level of detail by ring:\n",
		len(parts), buildings)
	fmt.Fprintf(s, "//   full < %d, medium < %d, far beyond.\n", m.FullRings, m.MediumRings)
	fmt.Fprintf(s, "// Regenerate: gnb geo make --name %s --at %.5f,%.5f --size %.0f --cells %d --profile %s --seed %d\n\n",
		m.Name, m.Lat, m.Lon, m.SizeM, m.Cells, m.Profile, m.Seed)
}

// writeMosaicCameras frames the whole area rather than one part. The overview
// eye sits far enough out to see the grid, which is exactly the case the
// engine's default 2 km far plane cannot draw — see FScadLoader, which now
// derives the far plane from the scene bounds.
func writeMosaicCameras(s *strings.Builder, m Mosaic, parts []PartScene) {
	half := m.SizeM / 2
	hi := math.Inf(-1)
	ground := 0.0
	best := 0.0
	tallest := [2]float64{0, 0}
	for _, p := range parts {
		_, b := p.Grid.Bounds()
		hi = math.Max(hi, b)
		if p.IR.Terrain != nil {
			ground = p.IR.Terrain.BaseElevation
		}
		for _, bl := range p.IR.Buildings {
			if bl.Height <= best {
				continue
			}
			c := Centroid(bl.Outer)
			if math.Abs(c[0]) > PartSizeM/2 || math.Abs(c[1]) > PartSizeM/2 {
				continue
			}
			best = bl.Height
			tallest = [2]float64{c[0] + p.Part.OffsetX, c[1] + p.Part.OffsetY}
		}
	}
	relief := hi - ground
	eyeZ := ground + math.Max(relief, best) + m.SizeM*0.45

	s.WriteString("// Camera markers (no geometry). The first one is the default view.\n")
	fmt.Fprintf(s, "gk_camera_lookat([%s, %s, %s], [0, 0, %s], \"overview\", 48);\n",
		fnum(-half*1.25), fnum(-half*1.45), fnum(eyeZ), fnum(ground+best*0.35))
	fmt.Fprintf(s, "gk_camera_lookat([%s, %s, %s], [%s, %s, %s], \"skyline\", 42);\n",
		fnum(tallest[0]-PartSizeM*0.9), fnum(tallest[1]-PartSizeM*1.1),
		fnum(ground+math.Max(best*0.55, 40)),
		fnum(tallest[0]), fnum(tallest[1]), fnum(ground+best*0.7))
	fmt.Fprintf(s, "gk_camera_lookat([%s, %s, %s], [%s, %s, %s], \"street\", 60);\n",
		fnum(tallest[0]+70), fnum(tallest[1]+70), fnum(ground+14.0),
		fnum(tallest[0]), fnum(tallest[1]), fnum(ground+6.0))
}

// EdgesFor says which sides of a part are the outer rim of the area.
func (m Mosaic) EdgesFor(p Part) Edges {
	g := m.Grid()
	return Edges{
		West: p.Col == 0, East: p.Col == g-1,
		South: p.Row == 0, North: p.Row == g-1,
	}
}
