package scadcompose

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"
)

// Catalog is the subset of assets/scad/lib/catalog.json (generated by
// `gnb scad catalog`) that composing needs: which kit owns which module,
// whether default-arg evaluation produced geometry, and each kit's scale class.
type Catalog struct {
	kits map[string]*catalogKit // key: short name ("old_city")
}

type catalogKit struct {
	file       string
	scaleClass string
	modules    map[string]bool // name -> ok (default-arg geometry exists)
}

// ShortKitName strips the "kit_" file prefix: "kit_old_city" -> "old_city".
func ShortKitName(name string) string {
	return strings.TrimPrefix(strings.TrimSuffix(name, ".scad"), "kit_")
}

// LoadCatalog parses catalog.json.
func LoadCatalog(path string) (*Catalog, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("cannot read kit catalog (run `gnb scad catalog` first): %w", err)
	}
	var doc struct {
		Kits []struct {
			Name       string `json:"name"`
			File       string `json:"file"`
			ScaleClass string `json:"scaleClass"`
			Modules    []struct {
				Name string `json:"name"`
				Ok   bool   `json:"ok"`
			} `json:"modules"`
		} `json:"kits"`
	}
	if err := json.Unmarshal(raw, &doc); err != nil {
		return nil, fmt.Errorf("%s: %w", path, err)
	}
	catalog := &Catalog{kits: map[string]*catalogKit{}}
	for _, kit := range doc.Kits {
		entry := &catalogKit{file: kit.File, scaleClass: kit.ScaleClass, modules: map[string]bool{}}
		for _, module := range kit.Modules {
			entry.modules[module.Name] = module.Ok
		}
		catalog.kits[ShortKitName(kit.Name)] = entry
	}
	return catalog, nil
}

// KitFile returns the kit's .scad filename ("kit_old_city.scad").
func (c *Catalog) KitFile(short string) (string, bool) {
	kit, ok := c.kits[short]
	if !ok {
		return "", false
	}
	return kit.file, true
}

// FindModule reports which kit (short name) defines the module and whether the
// module produced geometry with default args.
func (c *Catalog) FindModule(module string) (kit string, ok bool, found bool) {
	for short, entry := range c.kits {
		if okFlag, exists := entry.modules[module]; exists {
			return short, okFlag, true
		}
	}
	return "", false, false
}

// ScaleClass returns the kit's scale class ("city"/"mid"/"human").
func (c *Catalog) ScaleClass(short string) string {
	if kit, ok := c.kits[short]; ok {
		return kit.scaleClass
	}
	return ""
}
