// <auto-generated>
//     Generated by 'gnb csharpgen' from src/Modules/NextDotNet/ReflectionManifest.json.
//     Do not edit. Expose a property by registering it with REFLECT_COMPONENT, refreshing the
//     manifest ('gnb csharpgen --refresh'), and regenerating.
//     'gnb csharpgen --check' fails when this file is out of date.
// </auto-generated>

using GkNext.Interop;

namespace GkNext;

/// <summary>
/// Implemented by every generated component wrapper, so a node can be asked for one by type.
/// </summary>
/// <remarks>
/// Wrappers are readonly structs holding nothing but a node id, which is why
/// <c>node.Render.Visible = false</c> works despite operating on a returned copy: the assignment
/// goes straight through to the engine rather than mutating the struct.
/// </remarks>
public interface IComponentRef<TSelf> where TSelf : struct, IComponentRef<TSelf>
{
    /// <summary>Hash of the name the component is registered under in entt::meta.</summary>
    static abstract uint ComponentTypeId { get; }

    /// <summary>The registered name, for the bindings that address components by string.</summary>
    static abstract string ComponentTypeName { get; }

    static abstract TSelf FromNode(uint nodeId);
}

/// <summary>A handle to a scene node: its own reflected properties, plus its components.</summary>
/// <remarks>
/// Holds only an id, so it stays valid across frames but says nothing about whether the node still
/// exists. Node ids are only addressable once the scene is committed — inside
/// <c>BeforeSceneRebuild</c> a node's starting state belongs in the spec it is created with.
/// </remarks>
public readonly struct NodeRef(uint nodeId)
{
    public readonly uint Id = nodeId;

    /// <summary>Hash of "Node" in entt::meta.</summary>
    public const uint TypeId = 879231789u;

    public static NodeRef Invalid => new(NodeIds.Invalid);

    public bool IsValid => NodeIds.IsValid(Id);

    /// <summary>The first node in the committed scene carrying <typeparamref name="T"/>.</summary>
    public static NodeRef WithComponent<T>() where T : struct, IComponentRef<T>
        => new(Scene.FindNodeIdWithComponent(T.ComponentTypeName));

    public bool Has<T>() where T : struct, IComponentRef<T> => Component.Has(Id, T.ComponentTypeId);

    public T GetComponent<T>() where T : struct, IComponentRef<T> => T.FromNode(Id);

    /// <summary>Node instance id (Transform) Read-only.</summary>
    public uint InstanceId => Component.GetUInt32(Id, TypeId, 49567391u);

    /// <summary>Node layer (Metadata)</summary>
    public string Layer
    {
        get => Component.GetString(Id, TypeId, 2950437782u);
        set => Component.SetString(Id, TypeId, 2950437782u, value);
    }

    /// <summary>Node name (Transform) Read-only.</summary>
    public string Name => Component.GetString(Id, TypeId, 266367750u);

    /// <summary>Local rotation (Transform)</summary>
    public Vector4 Rotation
    {
        get => Component.GetQuat(Id, TypeId, 36861823u);
        set => Component.SetQuat(Id, TypeId, 36861823u, in value);
    }

    /// <summary>Local scale (Transform)</summary>
    public Vector3 Scale
    {
        get => Component.GetVec3(Id, TypeId, 676498961u);
        set => Component.SetVec3(Id, TypeId, 676498961u, in value);
    }

    /// <summary>Node tag (Metadata)</summary>
    public string Tag
    {
        get => Component.GetString(Id, TypeId, 4169356339u);
        set => Component.SetString(Id, TypeId, 4169356339u, value);
    }

    /// <summary>Local translation (Transform)</summary>
    public Vector3 Translation
    {
        get => Component.GetVec3(Id, TypeId, 613888204u);
        set => Component.SetVec3(Id, TypeId, 613888204u, in value);
    }

    // Shorthand for the components registered with the engine.
    public RenderComponent Render => new(Id);
    public EnvironmentComponent Environment => new(Id);
    public LightComponent Light => new(Id);
    public PhysicsComponent Physics => new(Id);
    public SkinnedMeshComponent SkinnedMesh => new(Id);
    public SceneReferenceComponent SceneReference => new(Id);
    public TerrainComponent Terrain => new(Id);
}

public readonly struct RenderComponent(uint nodeId) : IComponentRef<RenderComponent>
{
    public readonly uint Id = nodeId;

    /// <summary>Hash of "RenderComponent" in entt::meta.</summary>
    public const uint TypeId = 3393791048u;

    static uint IComponentRef<RenderComponent>.ComponentTypeId => TypeId;

    static string IComponentRef<RenderComponent>.ComponentTypeName => "RenderComponent";

    static RenderComponent IComponentRef<RenderComponent>.FromNode(uint nodeId) => new(nodeId);

    /// <summary>Whether the node this handle came from actually carries this component.</summary>
    public bool Exists => Component.Has(Id, TypeId);

    /// <summary>Whether the object casts shadows (Rendering)</summary>
    public bool CastShadows
    {
        get => Component.GetBool(Id, TypeId, 2207922471u);
        set => Component.SetBool(Id, TypeId, 2207922471u, value);
    }

    /// <summary>Whether the object is drawn in the main visibility pass (Rendering)</summary>
    public bool MainVisible
    {
        get => Component.GetBool(Id, TypeId, 191143274u);
        set => Component.SetBool(Id, TypeId, 191143274u, value);
    }

    /// <summary>The model resource (Mesh)</summary>
    public uint ModelId
    {
        get => Component.GetUInt32(Id, TypeId, 2704773975u);
        set => Component.SetUInt32(Id, TypeId, 2704773975u, value);
    }

    /// <summary>Whether the object is visible to raycasts (Rendering)</summary>
    public bool RayCastVisible
    {
        get => Component.GetBool(Id, TypeId, 1665393986u);
        set => Component.SetBool(Id, TypeId, 1665393986u, value);
    }

    /// <summary>Whether the object participates in GPU ray tracing acceleration structures (Rendering)</summary>
    public bool RayTraceVisible
    {
        get => Component.GetBool(Id, TypeId, 3917588094u);
        set => Component.SetBool(Id, TypeId, 3917588094u, value);
    }

    /// <summary>Whether the object receives global illumination (Rendering)</summary>
    public bool ReceiveGI
    {
        get => Component.GetBool(Id, TypeId, 4248519970u);
        set => Component.SetBool(Id, TypeId, 4248519970u, value);
    }

    /// <summary>Skinning data index for skeletal animation (Animation) Read-only.</summary>
    public int SkinIndex => Component.GetInt32(Id, TypeId, 1205595124u);

    /// <summary>Whether the object is visible (Rendering)</summary>
    public bool Visible
    {
        get => Component.GetBool(Id, TypeId, 1495943489u);
        set => Component.SetBool(Id, TypeId, 1495943489u, value);
    }

    // Reflected but not bound:
    //   Materials (Array) — arrays need element-level accessors, not a value copy
}

public readonly struct EnvironmentComponent(uint nodeId) : IComponentRef<EnvironmentComponent>
{
    public readonly uint Id = nodeId;

    /// <summary>Hash of "EnvironmentComponent" in entt::meta.</summary>
    public const uint TypeId = 3983330361u;

    static uint IComponentRef<EnvironmentComponent>.ComponentTypeId => TypeId;

    static string IComponentRef<EnvironmentComponent>.ComponentTypeName => "EnvironmentComponent";

    static EnvironmentComponent IComponentRef<EnvironmentComponent>.FromNode(uint nodeId) => new(nodeId);

    /// <summary>Whether the node this handle came from actually carries this component.</summary>
    public bool Exists => Component.Has(Id, TypeId);

    /// <summary>Apply atmospheric aerial perspective to scene geometry (Atmosphere)</summary>
    public bool AerialPerspectiveEnabled
    {
        get => Component.GetBool(Id, TypeId, 387175588u);
        set => Component.SetBool(Id, TypeId, 387175588u, value);
    }

    /// <summary>Aerial perspective range in world units (Atmosphere)</summary>
    public float AerialPerspectiveMaxDistance
    {
        get => Component.GetFloat(Id, TypeId, 3870206480u);
        set => Component.SetFloat(Id, TypeId, 3870206480u, value);
    }

    /// <summary>Enable the procedural atmosphere sky (Atmosphere)</summary>
    public bool AtmosphereEnabled
    {
        get => Component.GetBool(Id, TypeId, 1084452750u);
        set => Component.SetBool(Id, TypeId, 1084452750u, value);
    }

    /// <summary>Planet radius (km) (Atmosphere)</summary>
    public float BottomRadius
    {
        get => Component.GetFloat(Id, TypeId, 2891865288u);
        set => Component.SetFloat(Id, TypeId, 2891865288u, value);
    }

    /// <summary>Default scene camera control speed (Camera)</summary>
    public float ControlSpeed
    {
        get => Component.GetFloat(Id, TypeId, 1572793409u);
        set => Component.SetFloat(Id, TypeId, 1572793409u, value);
    }

    /// <summary>Fog base height in world units (Height Fog)</summary>
    public float FogBaseHeight
    {
        get => Component.GetFloat(Id, TypeId, 2827099729u);
        set => Component.SetFloat(Id, TypeId, 2827099729u, value);
    }

    /// <summary>Sea-level extinction density (Height Fog)</summary>
    public float FogDensity
    {
        get => Component.GetFloat(Id, TypeId, 2839077681u);
        set => Component.SetFloat(Id, TypeId, 2839077681u, value);
    }

    /// <summary>Exponential height falloff (Height Fog)</summary>
    public float FogHeightFalloff
    {
        get => Component.GetFloat(Id, TypeId, 1716069486u);
        set => Component.SetFloat(Id, TypeId, 1716069486u, value);
    }

    /// <summary>Height-fog in-scattering color (Height Fog)</summary>
    public Vector3 FogInscatteringColor
    {
        get => Component.GetVec3(Id, TypeId, 195291665u);
        set => Component.SetVec3(Id, TypeId, 195291665u, in value);
    }

    /// <summary>Maximum fog opacity (Height Fog)</summary>
    public float FogMaxOpacity
    {
        get => Component.GetFloat(Id, TypeId, 2261275876u);
        set => Component.SetFloat(Id, TypeId, 2261275876u, value);
    }

    /// <summary>Distance before fog begins (Height Fog)</summary>
    public float FogStartDistance
    {
        get => Component.GetFloat(Id, TypeId, 2194124594u);
        set => Component.SetFloat(Id, TypeId, 2194124594u, value);
    }

    /// <summary>Enable gamma correction (Environment)</summary>
    public bool GammaCorrection
    {
        get => Component.GetBool(Id, TypeId, 2108403150u);
        set => Component.SetBool(Id, TypeId, 2108403150u, value);
    }

    /// <summary>Planet ground albedo (Atmosphere)</summary>
    public Vector3 GroundAlbedo
    {
        get => Component.GetVec3(Id, TypeId, 1932013783u);
        set => Component.SetVec3(Id, TypeId, 1932013783u, in value);
    }

    /// <summary>Enable HDR sky lighting (Environment)</summary>
    public bool HasSky
    {
        get => Component.GetBool(Id, TypeId, 49852520u);
        set => Component.SetBool(Id, TypeId, 49852520u, value);
    }

    /// <summary>Enable directional sunlight (Environment)</summary>
    public bool HasSun
    {
        get => Component.GetBool(Id, TypeId, 432088995u);
        set => Component.SetBool(Id, TypeId, 432088995u, value);
    }

    /// <summary>Enable exponential height fog (Height Fog)</summary>
    public bool HeightFogEnabled
    {
        get => Component.GetBool(Id, TypeId, 3683330743u);
        set => Component.SetBool(Id, TypeId, 3683330743u, value);
    }

    /// <summary>Mie absorption coefficients (1/km) (Atmosphere)</summary>
    public Vector3 MieAbsorption
    {
        get => Component.GetVec3(Id, TypeId, 3277627131u);
        set => Component.SetVec3(Id, TypeId, 3277627131u, in value);
    }

    /// <summary>Mie density scale height (km) (Atmosphere)</summary>
    public float MieDensityH
    {
        get => Component.GetFloat(Id, TypeId, 1276607738u);
        set => Component.SetFloat(Id, TypeId, 1276607738u, value);
    }

    /// <summary>Henyey-Greenstein anisotropy (Atmosphere)</summary>
    public float MiePhaseG
    {
        get => Component.GetFloat(Id, TypeId, 1994066170u);
        set => Component.SetFloat(Id, TypeId, 1994066170u, value);
    }

    /// <summary>Mie scattering coefficients (1/km) (Atmosphere)</summary>
    public Vector3 MieScattering
    {
        get => Component.GetVec3(Id, TypeId, 1707658648u);
        set => Component.SetVec3(Id, TypeId, 1707658648u, in value);
    }

    /// <summary>Ozone absorption coefficients (1/km) (Atmosphere)</summary>
    public Vector3 OzoneAbsorption
    {
        get => Component.GetVec3(Id, TypeId, 4046689145u);
        set => Component.SetVec3(Id, TypeId, 4046689145u, in value);
    }

    /// <summary>Ozone layer center altitude (km) (Atmosphere)</summary>
    public float OzoneCenterAltitude
    {
        get => Component.GetFloat(Id, TypeId, 421270859u);
        set => Component.SetFloat(Id, TypeId, 421270859u, value);
    }

    /// <summary>Ozone layer half width (km) (Atmosphere)</summary>
    public float OzoneWidth
    {
        get => Component.GetFloat(Id, TypeId, 2743778364u);
        set => Component.SetFloat(Id, TypeId, 2743778364u, value);
    }

    /// <summary>Rayleigh density scale height (km) (Atmosphere)</summary>
    public float RayleighDensityH
    {
        get => Component.GetFloat(Id, TypeId, 3151995328u);
        set => Component.SetFloat(Id, TypeId, 3151995328u, value);
    }

    /// <summary>Rayleigh scattering coefficients (1/km) (Atmosphere)</summary>
    public Vector3 RayleighScattering
    {
        get => Component.GetVec3(Id, TypeId, 1769753322u);
        set => Component.SetVec3(Id, TypeId, 1769753322u, in value);
    }

    /// <summary>Sky lighting tint (Environment)</summary>
    public Vector3 SkyColor
    {
        get => Component.GetVec3(Id, TypeId, 263037657u);
        set => Component.SetVec3(Id, TypeId, 263037657u, in value);
    }

    /// <summary>HDR sky texture index (Environment)</summary>
    public int SkyIdx
    {
        get => Component.GetInt32(Id, TypeId, 2615143049u);
        set => Component.SetInt32(Id, TypeId, 2615143049u, value);
    }

    /// <summary>Sky lighting intensity (Environment)</summary>
    public float SkyIntensity
    {
        get => Component.GetFloat(Id, TypeId, 3743349703u);
        set => Component.SetFloat(Id, TypeId, 3743349703u, value);
    }

    /// <summary>Procedural sky luminance multiplier (Atmosphere)</summary>
    public float SkyLuminanceScale
    {
        get => Component.GetFloat(Id, TypeId, 2034213710u);
        set => Component.SetFloat(Id, TypeId, 2034213710u, value);
    }

    /// <summary>Horizontal sky rotation (Environment)</summary>
    public float SkyRotation
    {
        get => Component.GetFloat(Id, TypeId, 3206945724u);
        set => Component.SetFloat(Id, TypeId, 3206945724u, value);
    }

    /// <summary>Directional sunlight color (Environment)</summary>
    public Vector3 SunColor
    {
        get => Component.GetVec3(Id, TypeId, 2480114180u);
        set => Component.SetVec3(Id, TypeId, 2480114180u, in value);
    }

    /// <summary>Sun elevation in radians (Environment)</summary>
    public float SunElevation
    {
        get => Component.GetFloat(Id, TypeId, 4143095712u);
        set => Component.SetFloat(Id, TypeId, 4143095712u, value);
    }

    /// <summary>Sun light intensity (Environment)</summary>
    public float SunIntensity
    {
        get => Component.GetFloat(Id, TypeId, 1225170262u);
        set => Component.SetFloat(Id, TypeId, 1225170262u, value);
    }

    /// <summary>Sun azimuth rotation (Environment)</summary>
    public float SunRotation
    {
        get => Component.GetFloat(Id, TypeId, 317392707u);
        set => Component.SetFloat(Id, TypeId, 317392707u, value);
    }

    /// <summary>Atmosphere top radius (km) (Atmosphere)</summary>
    public float TopRadius
    {
        get => Component.GetFloat(Id, TypeId, 2693582434u);
        set => Component.SetFloat(Id, TypeId, 2693582434u, value);
    }

    /// <summary>Altitude of world y=0 (km) (Atmosphere)</summary>
    public float WorldOriginAltitude
    {
        get => Component.GetFloat(Id, TypeId, 1590130703u);
        set => Component.SetFloat(Id, TypeId, 1590130703u, value);
    }

    /// <summary>World-to-kilometre conversion (Atmosphere)</summary>
    public float WorldUnitsPerKm
    {
        get => Component.GetFloat(Id, TypeId, 3055890125u);
        set => Component.SetFloat(Id, TypeId, 3055890125u, value);
    }
}

public readonly struct LightComponent(uint nodeId) : IComponentRef<LightComponent>
{
    public readonly uint Id = nodeId;

    /// <summary>Hash of "LightComponent" in entt::meta.</summary>
    public const uint TypeId = 4257272042u;

    static uint IComponentRef<LightComponent>.ComponentTypeId => TypeId;

    static string IComponentRef<LightComponent>.ComponentTypeName => "LightComponent";

    static LightComponent IComponentRef<LightComponent>.FromNode(uint nodeId) => new(nodeId);

    /// <summary>Whether the node this handle came from actually carries this component.</summary>
    public bool Exists => Component.Has(Id, TypeId);

    /// <summary>Whether this light emits (Light)</summary>
    public bool Enabled
    {
        get => Component.GetBool(Id, TypeId, 2626085950u);
        set => Component.SetBool(Id, TypeId, 2626085950u, value);
    }

    /// <summary>Number of light primitives on this node (Light) Read-only.</summary>
    public uint LightCount => Component.GetUInt32(Id, TypeId, 2939991638u);

    /// <summary>0 = area, 1 = point (Light)</summary>
    public uint LightType
    {
        get => Component.GetUInt32(Id, TypeId, 2404094935u);
        set => Component.SetUInt32(Id, TypeId, 2404094935u, value);
    }

    /// <summary>Diffuse-light material index (Light)</summary>
    public uint MaterialIndex
    {
        get => Component.GetUInt32(Id, TypeId, 3183644636u);
        set => Component.SetUInt32(Id, TypeId, 3183644636u, value);
    }

    /// <summary>Local normal in xyz and sampling area in w (Light Geometry)</summary>
    public Vector4 NormalArea
    {
        get => Component.GetVec4(Id, TypeId, 3768954967u);
        set => Component.SetVec4(Id, TypeId, 3768954967u, in value);
    }

    /// <summary>Area corner or point position/radius (Light Geometry)</summary>
    public Vector4 P0
    {
        get => Component.GetVec4(Id, TypeId, 553643949u);
        set => Component.SetVec4(Id, TypeId, 553643949u, in value);
    }

    /// <summary>Second area-light corner (Light Geometry)</summary>
    public Vector4 P1
    {
        get => Component.GetVec4(Id, TypeId, 536866330u);
        set => Component.SetVec4(Id, TypeId, 536866330u, in value);
    }

    /// <summary>Third area-light corner (Light Geometry)</summary>
    public Vector4 P3
    {
        get => Component.GetVec4(Id, TypeId, 503311092u);
        set => Component.SetVec4(Id, TypeId, 503311092u, in value);
    }
}

public readonly struct PhysicsComponent(uint nodeId) : IComponentRef<PhysicsComponent>
{
    public readonly uint Id = nodeId;

    /// <summary>Hash of "PhysicsComponent" in entt::meta.</summary>
    public const uint TypeId = 338477249u;

    static uint IComponentRef<PhysicsComponent>.ComponentTypeId => TypeId;

    static string IComponentRef<PhysicsComponent>.ComponentTypeName => "PhysicsComponent";

    static PhysicsComponent IComponentRef<PhysicsComponent>.FromNode(uint nodeId) => new(nodeId);

    /// <summary>Whether the node this handle came from actually carries this component.</summary>
    public bool Exists => Component.Has(Id, TypeId);

    /// <summary>Angular velocity damping (Physics)</summary>
    public float AngularDamping
    {
        get => Component.GetFloat(Id, TypeId, 527193057u);
        set => Component.SetFloat(Id, TypeId, 527193057u, value);
    }

    /// <summary>Collision response preset (Physics)</summary>
    public string CollisionPresets
    {
        get => Component.GetString(Id, TypeId, 1479790545u);
        set => Component.SetString(Id, TypeId, 1479790545u, value);
    }

    /// <summary>Apply gravity to this body (Physics)</summary>
    public bool EnableGravity
    {
        get => Component.GetBool(Id, TypeId, 500762548u);
        set => Component.SetBool(Id, TypeId, 500762548u, value);
    }

    /// <summary>Linear velocity damping (Physics)</summary>
    public float LinearDamping
    {
        get => Component.GetFloat(Id, TypeId, 427950278u);
        set => Component.SetFloat(Id, TypeId, 427950278u, value);
    }

    /// <summary>Physics material preset (Physics)</summary>
    public string PhysicsMaterial
    {
        get => Component.GetString(Id, TypeId, 2749179543u);
        set => Component.SetString(Id, TypeId, 2749179543u, value);
    }

    /// <summary>Offset from node origin for physics body (Physics)</summary>
    public Vector3 PhysicsOffset
    {
        get => Component.GetVec3(Id, TypeId, 1677701989u);
        set => Component.SetVec3(Id, TypeId, 1677701989u, in value);
    }

    /// <summary>Enable dynamic rigid-body simulation (Physics)</summary>
    public bool SimulatePhysics
    {
        get => Component.GetBool(Id, TypeId, 1284827756u);
        set => Component.SetBool(Id, TypeId, 1284827756u, value);
    }

    // Reflected but not bound:
    //   Mobility (Enum) — enum properties would need generated enum types; the manifest carries only a type id
}

public readonly struct SkinnedMeshComponent(uint nodeId) : IComponentRef<SkinnedMeshComponent>
{
    public readonly uint Id = nodeId;

    /// <summary>Hash of "SkinnedMeshComponent" in entt::meta.</summary>
    public const uint TypeId = 3847717573u;

    static uint IComponentRef<SkinnedMeshComponent>.ComponentTypeId => TypeId;

    static string IComponentRef<SkinnedMeshComponent>.ComponentTypeName => "SkinnedMeshComponent";

    static SkinnedMeshComponent IComponentRef<SkinnedMeshComponent>.FromNode(uint nodeId) => new(nodeId);

    /// <summary>Whether the node this handle came from actually carries this component.</summary>
    public bool Exists => Component.Has(Id, TypeId);

    /// <summary>Name of the currently playing animation (Animation) Read-only.</summary>
    public string CurrentAnimation => Component.GetString(Id, TypeId, 2069512920u);

    /// <summary>Whether an animation is currently playing (Animation) Read-only.</summary>
    public bool IsPlaying => Component.GetBool(Id, TypeId, 3836956773u);

    /// <summary>Animation playback speed multiplier (Animation)</summary>
    public float PlaySpeed
    {
        get => Component.GetFloat(Id, TypeId, 1962350526u);
        set => Component.SetFloat(Id, TypeId, 1962350526u, value);
    }
}

public readonly struct SceneReferenceComponent(uint nodeId) : IComponentRef<SceneReferenceComponent>
{
    public readonly uint Id = nodeId;

    /// <summary>Hash of "SceneReferenceComponent" in entt::meta.</summary>
    public const uint TypeId = 1130626983u;

    static uint IComponentRef<SceneReferenceComponent>.ComponentTypeId => TypeId;

    static string IComponentRef<SceneReferenceComponent>.ComponentTypeName => "SceneReferenceComponent";

    static SceneReferenceComponent IComponentRef<SceneReferenceComponent>.FromNode(uint nodeId) => new(nodeId);

    /// <summary>Whether the node this handle came from actually carries this component.</summary>
    public bool Exists => Component.Has(Id, TypeId);

    /// <summary>Referenced scene asset path (Scene Reference)</summary>
    public string AssetPath
    {
        get => Component.GetString(Id, TypeId, 3880040812u);
        set => Component.SetString(Id, TypeId, 3880040812u, value);
    }

    /// <summary>Last reference load error (Scene Reference) Read-only.</summary>
    public string Error => Component.GetString(Id, TypeId, 4086144241u);

    /// <summary>Number of internal nodes loaded from the asset (Scene Reference) Read-only.</summary>
    public uint LoadedNodeCount => Component.GetUInt32(Id, TypeId, 3409791187u);

    /// <summary>Normalized referenced asset path (Scene Reference) Read-only.</summary>
    public string ResolvedPath => Component.GetString(Id, TypeId, 1541864310u);

    /// <summary>Reference load status (Scene Reference) Read-only.</summary>
    public string Status => Component.GetString(Id, TypeId, 6222351u);
}

public readonly struct TerrainComponent(uint nodeId) : IComponentRef<TerrainComponent>
{
    public readonly uint Id = nodeId;

    /// <summary>Hash of "TerrainComponent" in entt::meta.</summary>
    public const uint TypeId = 1338567229u;

    static uint IComponentRef<TerrainComponent>.ComponentTypeId => TypeId;

    static string IComponentRef<TerrainComponent>.ComponentTypeName => "TerrainComponent";

    static TerrainComponent IComponentRef<TerrainComponent>.FromNode(uint nodeId) => new(nodeId);

    /// <summary>Whether the node this handle came from actually carries this component.</summary>
    public bool Exists => Component.Has(Id, TypeId);

    /// <summary>Heightfield cells along local X (Terrain) Read-only.</summary>
    public int CellsX => Component.GetInt32(Id, TypeId, 3884278206u);

    /// <summary>Heightfield cells along local Y (Terrain) Read-only.</summary>
    public int CellsY => Component.GetInt32(Id, TypeId, 3901055825u);

    /// <summary>Deterministic generation seed (Terrain) Read-only.</summary>
    public int Seed => Component.GetInt32(Id, TypeId, 3497134284u);

    /// <summary>Local domain size along X (Terrain) Read-only.</summary>
    public float SizeX => Component.GetFloat(Id, TypeId, 3869557420u);

    /// <summary>Local domain size along Y (Terrain) Read-only.</summary>
    public float SizeY => Component.GetFloat(Id, TypeId, 3886335039u);
}
