// <auto-generated>
//     Generated by 'gnb csharpgen' from src/Modules/NextDotNet/EngineApi.def.h.
//     Do not edit. Add a binding by adding a line to the def file and regenerating.
//     'gnb csharpgen --check' fails when this file is out of date.
// </auto-generated>

using System.Runtime.InteropServices;
using GkNext.Interop;

namespace GkNext.Interop
{
    /// <summary>
    /// Native services handed to managed code at bootstrap. Layout must match FEngineApi in
    /// src/Modules/NextDotNet/Interop.h exactly; both are expanded from the same def file.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct FEngineApi
    {
        public uint Version;

        public delegate* unmanaged<GkStr, void> Log_Info;
        public delegate* unmanaged<GkStr, void> Log_Warn;
        public delegate* unmanaged<GkStr, void> Log_Error;
        public delegate* unmanaged<uint> Engine_GetTotalFrames;
        public delegate* unmanaged<double> Engine_GetTime;
        public delegate* unmanaged<double> Engine_GetDeltaSeconds;
        public delegate* unmanaged<double> Engine_GetSmoothDeltaSeconds;
        public delegate* unmanaged<GkStr, void> Engine_RequestLoadScene;
        public delegate* unmanaged<void> Engine_RequestClose;
        public delegate* unmanaged<int> Engine_IsReplayMode;
        public delegate* unmanaged<GkStr, int> Input_IsKeyDown;
        public delegate* unmanaged<GkStr, int> Input_IsKeyPressed;
        public delegate* unmanaged<int, int> Input_IsMouseButtonDown;
        public delegate* unmanaged<int, int> Input_IsMouseButtonPressed;
        public delegate* unmanaged<GkStr, int> Input_IsGamepadButtonDown;
        public delegate* unmanaged<GkStr, float, void> Audio_PlaySfx;
        public delegate* unmanaged<GkStr, float, void> Audio_PlayMusic;
        public delegate* unmanaged<void> Audio_StopMusic;
        public delegate* unmanaged<GkStr, int, int> UI_Begin;
        public delegate* unmanaged<void> UI_End;
        public delegate* unmanaged<GkStr, void> UI_Text;
        public delegate* unmanaged<float, float, void> UI_SetCursorPos;
        public delegate* unmanaged<Vector2*, void> UI_GetWindowSize;
        public delegate* unmanaged<float, void> UI_SetWindowFontScale;
        public delegate* unmanaged<Vector2*, void> UI_GetScreenSize;
        public delegate* unmanaged<GkStr, float, Vector2*, void> UI_CalcTextSize;
        public delegate* unmanaged<GkStr, float, float, uint, float, void> UI_DrawText;
        public delegate* unmanaged<float, float, float, float, uint, float, void> UI_DrawRectFilled;
        public delegate* unmanaged<float, float, float, float, uint, float, float, void> UI_DrawRect;
        public delegate* unmanaged<uint> Scene_GetIndicesCount;
        public delegate* unmanaged<GkStr, uint> Scene_FindNodeIdWithComponent;
        public delegate* unmanaged<GkStr, RenderNodeSpec*, uint> Scene_AddRenderNode;
        public delegate* unmanaged<uint, void> Scene_RemoveNodeById;
        public delegate* unmanaged<void> Scene_MarkTransformDirty;
        public delegate* unmanaged<uint, int, void> Scene_RecalcNodeTransform;
        public delegate* unmanaged<uint, Vector3*, void> Scene_SetNodeTranslation;
        public delegate* unmanaged<uint, Vector3*, void> Scene_SetNodeScale;
        public delegate* unmanaged<uint, int, void> Scene_SetNodeVisible;
        public delegate* unmanaged<Vector3*, Vector3*, uint> SceneBuild_AddBoxModel;
        public delegate* unmanaged<Vector3*, float, uint> SceneBuild_AddSphereModel;
        public delegate* unmanaged<Vector3*, uint> SceneBuild_AddLambertianMaterial;
        public delegate* unmanaged<Vector3*, float, uint> SceneBuild_AddDiffuseLightMaterial;
        public delegate* unmanaged<GkStr, RenderNodeSpec*, uint> SceneBuild_AddRenderNode;
        public delegate* unmanaged<byte*, int, int> Paths_GetProjectRoot;
        public delegate* unmanaged<byte*, int, int> Paths_GetOutputDir;
        public delegate* unmanaged<GkStr, byte*, int, int> Assets_ReadFile;
    }

    /// <summary>Number of bindings in the table, checked against the native side.</summary>
    public static class EngineApiInfo
    {
        public const int EntryCount = 46;
    }
}

namespace GkNext
{
    public static unsafe class Log
    {
        public static void Info(string message)
        {
            var mark = Utf8Arena.Mark();
            try
            {
                Api.Table->Log_Info(Utf8Arena.Encode(message));
            }
            finally
            {
                Utf8Arena.Release(mark);
            }
        }

        public static void Warn(string message)
        {
            var mark = Utf8Arena.Mark();
            try
            {
                Api.Table->Log_Warn(Utf8Arena.Encode(message));
            }
            finally
            {
                Utf8Arena.Release(mark);
            }
        }

        public static void Error(string message)
        {
            var mark = Utf8Arena.Mark();
            try
            {
                Api.Table->Log_Error(Utf8Arena.Encode(message));
            }
            finally
            {
                Utf8Arena.Release(mark);
            }
        }
    }

    public static unsafe class Engine
    {
        public static uint GetTotalFrames()
        {
            return Api.Table->Engine_GetTotalFrames();
        }

        public static double GetTime()
        {
            return Api.Table->Engine_GetTime();
        }

        public static double GetDeltaSeconds()
        {
            return Api.Table->Engine_GetDeltaSeconds();
        }

        public static double GetSmoothDeltaSeconds()
        {
            return Api.Table->Engine_GetSmoothDeltaSeconds();
        }

        public static void RequestLoadScene(string filename)
        {
            var mark = Utf8Arena.Mark();
            try
            {
                Api.Table->Engine_RequestLoadScene(Utf8Arena.Encode(filename));
            }
            finally
            {
                Utf8Arena.Release(mark);
            }
        }

        public static void RequestClose()
        {
            Api.Table->Engine_RequestClose();
        }

        public static bool IsReplayMode()
        {
            return Api.Table->Engine_IsReplayMode() != 0;
        }
    }

    public static unsafe class Input
    {
        public static bool IsKeyDown(string name)
        {
            var mark = Utf8Arena.Mark();
            try
            {
                return Api.Table->Input_IsKeyDown(Utf8Arena.Encode(name)) != 0;
            }
            finally
            {
                Utf8Arena.Release(mark);
            }
        }

        public static bool IsKeyPressed(string name)
        {
            var mark = Utf8Arena.Mark();
            try
            {
                return Api.Table->Input_IsKeyPressed(Utf8Arena.Encode(name)) != 0;
            }
            finally
            {
                Utf8Arena.Release(mark);
            }
        }

        public static bool IsMouseButtonDown(int button)
        {
            return Api.Table->Input_IsMouseButtonDown(button) != 0;
        }

        public static bool IsMouseButtonPressed(int button)
        {
            return Api.Table->Input_IsMouseButtonPressed(button) != 0;
        }

        public static bool IsGamepadButtonDown(string name)
        {
            var mark = Utf8Arena.Mark();
            try
            {
                return Api.Table->Input_IsGamepadButtonDown(Utf8Arena.Encode(name)) != 0;
            }
            finally
            {
                Utf8Arena.Release(mark);
            }
        }
    }

    public static unsafe class Audio
    {
        public static void PlaySfx(string path, float volume = 1.0f)
        {
            var mark = Utf8Arena.Mark();
            try
            {
                Api.Table->Audio_PlaySfx(Utf8Arena.Encode(path), volume);
            }
            finally
            {
                Utf8Arena.Release(mark);
            }
        }

        public static void PlayMusic(string path, float volume = 1.0f)
        {
            var mark = Utf8Arena.Mark();
            try
            {
                Api.Table->Audio_PlayMusic(Utf8Arena.Encode(path), volume);
            }
            finally
            {
                Utf8Arena.Release(mark);
            }
        }

        public static void StopMusic()
        {
            Api.Table->Audio_StopMusic();
        }
    }

    public static unsafe class UI
    {
        public static bool Begin(string name, int flags = 0)
        {
            var mark = Utf8Arena.Mark();
            try
            {
                return Api.Table->UI_Begin(Utf8Arena.Encode(name), flags) != 0;
            }
            finally
            {
                Utf8Arena.Release(mark);
            }
        }

        public static void End()
        {
            Api.Table->UI_End();
        }

        public static void Text(string text)
        {
            var mark = Utf8Arena.Mark();
            try
            {
                Api.Table->UI_Text(Utf8Arena.Encode(text));
            }
            finally
            {
                Utf8Arena.Release(mark);
            }
        }

        public static void SetCursorPos(float x, float y)
        {
            Api.Table->UI_SetCursorPos(x, y);
        }

        public static Vector2 GetWindowSize()
        {
            Vector2 result = default;
            Api.Table->UI_GetWindowSize(&result);
            return result;
        }

        public static void SetWindowFontScale(float scale)
        {
            Api.Table->UI_SetWindowFontScale(scale);
        }

        public static Vector2 GetScreenSize()
        {
            Vector2 result = default;
            Api.Table->UI_GetScreenSize(&result);
            return result;
        }

        public static Vector2 CalcTextSize(string text, float scale = 1.0f)
        {
            var mark = Utf8Arena.Mark();
            try
            {
                Vector2 result = default;
                Api.Table->UI_CalcTextSize(Utf8Arena.Encode(text), scale, &result);
                return result;
            }
            finally
            {
                Utf8Arena.Release(mark);
            }
        }

        public static void DrawText(string text, float x, float y, Color color, float scale = 1.0f)
        {
            var mark = Utf8Arena.Mark();
            try
            {
                Api.Table->UI_DrawText(Utf8Arena.Encode(text), x, y, color.ToPacked(), scale);
            }
            finally
            {
                Utf8Arena.Release(mark);
            }
        }

        public static void DrawRectFilled(float x, float y, float width, float height, Color color, float rounding = 0.0f)
        {
            Api.Table->UI_DrawRectFilled(x, y, width, height, color.ToPacked(), rounding);
        }

        public static void DrawRect(float x, float y, float width, float height, Color color, float rounding = 0.0f, float thickness = 1.0f)
        {
            Api.Table->UI_DrawRect(x, y, width, height, color.ToPacked(), rounding, thickness);
        }
    }

    public static unsafe class Scene
    {
        public static uint GetIndicesCount()
        {
            return Api.Table->Scene_GetIndicesCount();
        }

        public static uint FindNodeIdWithComponent(string componentType)
        {
            var mark = Utf8Arena.Mark();
            try
            {
                return Api.Table->Scene_FindNodeIdWithComponent(Utf8Arena.Encode(componentType));
            }
            finally
            {
                Utf8Arena.Release(mark);
            }
        }

        public static uint AddRenderNode(string name, in RenderNodeSpec spec)
        {
            var mark = Utf8Arena.Mark();
            try
            {
                fixed (RenderNodeSpec* p_spec = &spec)
                {
                    return Api.Table->Scene_AddRenderNode(Utf8Arena.Encode(name), p_spec);
                }
            }
            finally
            {
                Utf8Arena.Release(mark);
            }
        }

        public static void RemoveNodeById(uint nodeId)
        {
            Api.Table->Scene_RemoveNodeById(nodeId);
        }

        public static void MarkTransformDirty()
        {
            Api.Table->Scene_MarkTransformDirty();
        }

        public static void RecalcNodeTransform(uint nodeId, bool full = false)
        {
            Api.Table->Scene_RecalcNodeTransform(nodeId, full ? 1 : 0);
        }

        public static void SetNodeTranslation(uint nodeId, in Vector3 translation)
        {
            fixed (Vector3* p_translation = &translation)
            {
                Api.Table->Scene_SetNodeTranslation(nodeId, p_translation);
            }
        }

        public static void SetNodeScale(uint nodeId, in Vector3 scale)
        {
            fixed (Vector3* p_scale = &scale)
            {
                Api.Table->Scene_SetNodeScale(nodeId, p_scale);
            }
        }

        public static void SetNodeVisible(uint nodeId, bool visible)
        {
            Api.Table->Scene_SetNodeVisible(nodeId, visible ? 1 : 0);
        }
    }

    public static unsafe class SceneBuild
    {
        public static uint AddBoxModel(in Vector3 min, in Vector3 max)
        {
            fixed (Vector3* p_min = &min)
            {
                fixed (Vector3* p_max = &max)
                {
                    return Api.Table->SceneBuild_AddBoxModel(p_min, p_max);
                }
            }
        }

        public static uint AddSphereModel(in Vector3 center, float radius)
        {
            fixed (Vector3* p_center = &center)
            {
                return Api.Table->SceneBuild_AddSphereModel(p_center, radius);
            }
        }

        public static uint AddLambertianMaterial(in Vector3 color)
        {
            fixed (Vector3* p_color = &color)
            {
                return Api.Table->SceneBuild_AddLambertianMaterial(p_color);
            }
        }

        public static uint AddDiffuseLightMaterial(in Vector3 color, float intensity = 1.0f)
        {
            fixed (Vector3* p_color = &color)
            {
                return Api.Table->SceneBuild_AddDiffuseLightMaterial(p_color, intensity);
            }
        }

        public static uint AddRenderNode(string name, in RenderNodeSpec spec)
        {
            var mark = Utf8Arena.Mark();
            try
            {
                fixed (RenderNodeSpec* p_spec = &spec)
                {
                    return Api.Table->SceneBuild_AddRenderNode(Utf8Arena.Encode(name), p_spec);
                }
            }
            finally
            {
                Utf8Arena.Release(mark);
            }
        }
    }

    public static unsafe class Paths
    {
        public static string GetProjectRoot()
        {
            int required = Api.Table->Paths_GetProjectRoot(null, 0);
            if (required <= 0)
            {
                return string.Empty;
            }
            byte[] buffer = new byte[required];
            fixed (byte* bufferPtr = buffer)
            {
                int written = Api.Table->Paths_GetProjectRoot(bufferPtr, required);
                return written <= 0 ? string.Empty : System.Text.Encoding.UTF8.GetString(bufferPtr, written);
            }
        }

        public static string GetOutputDir()
        {
            int required = Api.Table->Paths_GetOutputDir(null, 0);
            if (required <= 0)
            {
                return string.Empty;
            }
            byte[] buffer = new byte[required];
            fixed (byte* bufferPtr = buffer)
            {
                int written = Api.Table->Paths_GetOutputDir(bufferPtr, required);
                return written <= 0 ? string.Empty : System.Text.Encoding.UTF8.GetString(bufferPtr, written);
            }
        }
    }

    public static unsafe class Assets
    {
        public static byte[] ReadFile(string path)
        {
            var mark = Utf8Arena.Mark();
            try
            {
                int required = Api.Table->Assets_ReadFile(Utf8Arena.Encode(path), null, 0);
                if (required <= 0)
                {
                    return System.Array.Empty<byte>();
                }
                byte[] buffer = new byte[required];
                fixed (byte* bufferPtr = buffer)
                {
                    int written = Api.Table->Assets_ReadFile(Utf8Arena.Encode(path), bufferPtr, required);
                    if (written == required)
                    {
                        return buffer;
                    }
                    return written <= 0 ? System.Array.Empty<byte>() : buffer.AsSpan(0, written).ToArray();
                }
            }
            finally
            {
                Utf8Arena.Release(mark);
            }
        }
    }
}
