// <auto-generated>
//     Generated by 'gnb csharpgen' from src/Modules/NextDotNet/EngineApi.def.h.
//     Do not edit. Add a binding by adding a line to the def file and regenerating.
//     'gnb csharpgen --check' fails when this file is out of date.
// </auto-generated>

using System.Runtime.InteropServices;
using GkNext.Interop;

namespace GkNext.Interop
{
    /// <summary>
    /// Native services handed to managed code at bootstrap. Layout must match FEngineApi in
    /// src/Modules/NextDotNet/Interop.h exactly; both are expanded from the same def file.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct FEngineApi
    {
        public uint Version;

        public delegate* unmanaged<GkStr, void> Log_Info;
        public delegate* unmanaged<GkStr, void> Log_Warn;
        public delegate* unmanaged<GkStr, void> Log_Error;
        public delegate* unmanaged<uint> Engine_GetTotalFrames;
        public delegate* unmanaged<double> Engine_GetTime;
        public delegate* unmanaged<double> Engine_GetDeltaSeconds;
        public delegate* unmanaged<double> Engine_GetSmoothDeltaSeconds;
        public delegate* unmanaged<GkStr, void> Engine_RequestLoadScene;
        public delegate* unmanaged<void> Engine_RequestClose;
        public delegate* unmanaged<int> Engine_IsReplayMode;
        public delegate* unmanaged<GkStr, int> Input_IsKeyDown;
        public delegate* unmanaged<GkStr, int> Input_IsKeyPressed;
        public delegate* unmanaged<int, int> Input_IsMouseButtonDown;
        public delegate* unmanaged<int, int> Input_IsMouseButtonPressed;
        public delegate* unmanaged<GkStr, int> Input_IsGamepadButtonDown;
        public delegate* unmanaged<Vector2*, void> Input_GetMousePosition;
        public delegate* unmanaged<int, float> Input_GetGamepadAxis;
        public delegate* unmanaged<GkStr, float, void> Audio_PlaySfx;
        public delegate* unmanaged<GkStr, float, uint, void> Audio_PlaySfxEx;
        public delegate* unmanaged<GkStr, float, void> Audio_PlayMusic;
        public delegate* unmanaged<void> Audio_StopMusic;
        public delegate* unmanaged<float, void> Audio_SetMusicVolume;
        public delegate* unmanaged<int> Physics_IsAvailable;
        public delegate* unmanaged<int, void> Physics_SetWorldPaused;
        public delegate* unmanaged<int> Physics_IsWorldPaused;
        public delegate* unmanaged<Vector3*, float, PhysicsMotionType, uint> Physics_CreateSphereBody;
        public delegate* unmanaged<Vector3*, Vector4*, Vector3*, PhysicsMotionType, uint> Physics_CreateBoxBody;
        public delegate* unmanaged<uint, void> Physics_RemoveBody;
        public delegate* unmanaged<uint, int, void> Physics_SetBodyActive;
        public delegate* unmanaged<uint, Vector3*, Vector4*, int, void> Physics_SetBodyTransform;
        public delegate* unmanaged<uint, Vector3*, Vector4*, float, void> Physics_MoveKinematicBody;
        public delegate* unmanaged<uint, Vector3*, Vector3*, void> Physics_SetBodyVelocity;
        public delegate* unmanaged<uint, Vector3*, void> Physics_AddForceToBody;
        public delegate* unmanaged<uint, PhysicsBodyState*, void> Physics_GetBodyState;
        public delegate* unmanaged<int> Rig_IsAvailable;
        public delegate* unmanaged<GkStr, int, uint> Rig_DeclarePool;
        public delegate* unmanaged<uint, GkStr, int> Rig_HasClip;
        public delegate* unmanaged<uint, Vector3*, float, Vector3*, uint> Rig_Acquire;
        public delegate* unmanaged<uint, void> Rig_Release;
        public delegate* unmanaged<uint, int> Rig_IsAlive;
        public delegate* unmanaged<uint, Vector3*, float, void> Rig_SetTransform;
        public delegate* unmanaged<uint, int, void> Rig_SetVisible;
        public delegate* unmanaged<uint, GkStr, float, void> Rig_PlayClip;
        public delegate* unmanaged<uint, float, void> Rig_SetPlaySpeed;
        public delegate* unmanaged<uint, uint> Rig_GetRootNodeId;
        public delegate* unmanaged<uint, GkStr, uint> Rig_GetBoneNodeId;
        public delegate* unmanaged<GkStr, int, int> UI_Begin;
        public delegate* unmanaged<void> UI_End;
        public delegate* unmanaged<GkStr, void> UI_Text;
        public delegate* unmanaged<float, float, void> UI_SetCursorPos;
        public delegate* unmanaged<Vector2*, void> UI_GetWindowSize;
        public delegate* unmanaged<float, void> UI_SetWindowFontScale;
        public delegate* unmanaged<Vector2*, void> UI_GetScreenSize;
        public delegate* unmanaged<GkStr, float, Vector2*, void> UI_CalcTextSize;
        public delegate* unmanaged<GkStr, float, float, uint, float, void> UI_DrawText;
        public delegate* unmanaged<float, float, float, float, uint, float, void> UI_DrawRectFilled;
        public delegate* unmanaged<float, float, float, float, uint, float, float, void> UI_DrawRect;
        public delegate* unmanaged<GkStr, int, int, UiTexture*, void> UI_RequestTexture;
        public delegate* unmanaged<UiDrawCommand*, int, Vector2*, int, byte*, int, void> UI_SubmitDrawList;
        public delegate* unmanaged<uint> Scene_GetIndicesCount;
        public delegate* unmanaged<GkStr, uint> Scene_FindNodeIdWithComponent;
        public delegate* unmanaged<GkStr, RenderNodeSpec*, uint> Scene_AddRenderNode;
        public delegate* unmanaged<uint, void> Scene_RemoveNodeById;
        public delegate* unmanaged<void> Scene_MarkTransformDirty;
        public delegate* unmanaged<uint, int, void> Scene_RecalcNodeTransform;
        public delegate* unmanaged<uint, Vector3*, void> Scene_SetNodeTranslation;
        public delegate* unmanaged<uint, Vector4*, void> Scene_SetNodeRotation;
        public delegate* unmanaged<uint, Vector3*, void> Scene_SetNodeScale;
        public delegate* unmanaged<NodeTransform*, void> Scene_SetNodeTransform;
        public delegate* unmanaged<NodeTransform*, int, void> Scene_SetNodeTransforms;
        public delegate* unmanaged<uint, int, void> Scene_SetNodeVisible;
        public delegate* unmanaged<uint, int, void> Scene_SetNodeVisibleRecursive;
        public delegate* unmanaged<uint, uint, int> Scene_SetNodeParent;
        public delegate* unmanaged<uint, uint, void> Scene_SetNodePrimaryMaterial;
        public delegate* unmanaged<uint, uint, void> Scene_SetNodeMaterialRecursive;
        public delegate* unmanaged<uint, uint, void> Scene_SetNodeOutlineFlags;
        public delegate* unmanaged<Vector3*, uint> Scene_AddLambertianMaterial;
        public delegate* unmanaged<Vector3*, float, uint> Scene_AddDiffuseLightMaterial;
        public delegate* unmanaged<uint, uint, NodeMobility, int> Scene_BindPhysicsBody;
        public delegate* unmanaged<uint> Scene_GetEnvironmentNodeId;
        public delegate* unmanaged<Vector3*, Vector3*, uint> SceneBuild_AddBoxModel;
        public delegate* unmanaged<Vector3*, float, uint> SceneBuild_AddSphereModel;
        public delegate* unmanaged<Vector3*, uint> SceneBuild_AddLambertianMaterial;
        public delegate* unmanaged<Vector3*, float, uint> SceneBuild_AddDiffuseLightMaterial;
        public delegate* unmanaged<GkStr, RenderNodeSpec*, uint> SceneBuild_AddRenderNode;
        public delegate* unmanaged<uint, uint, NodeMobility, int> SceneBuild_BindPhysicsBody;
        public delegate* unmanaged<byte*, int, int> Paths_GetProjectRoot;
        public delegate* unmanaged<byte*, int, int> Paths_GetOutputDir;
        public delegate* unmanaged<GkStr, byte*, int, int> Assets_ReadFile;
        public delegate* unmanaged<uint, uint, int> Component_Has;
        public delegate* unmanaged<uint, uint, uint, int> Component_GetBool;
        public delegate* unmanaged<uint, uint, uint, int, void> Component_SetBool;
        public delegate* unmanaged<uint, uint, uint, int> Component_GetInt32;
        public delegate* unmanaged<uint, uint, uint, int, void> Component_SetInt32;
        public delegate* unmanaged<uint, uint, uint, uint> Component_GetUInt32;
        public delegate* unmanaged<uint, uint, uint, uint, void> Component_SetUInt32;
        public delegate* unmanaged<uint, uint, uint, float> Component_GetFloat;
        public delegate* unmanaged<uint, uint, uint, float, void> Component_SetFloat;
        public delegate* unmanaged<uint, uint, uint, double> Component_GetDouble;
        public delegate* unmanaged<uint, uint, uint, double, void> Component_SetDouble;
        public delegate* unmanaged<uint, uint, uint, Vector2*, void> Component_GetVec2;
        public delegate* unmanaged<uint, uint, uint, Vector2*, void> Component_SetVec2;
        public delegate* unmanaged<uint, uint, uint, Vector3*, void> Component_GetVec3;
        public delegate* unmanaged<uint, uint, uint, Vector3*, void> Component_SetVec3;
        public delegate* unmanaged<uint, uint, uint, Vector4*, void> Component_GetVec4;
        public delegate* unmanaged<uint, uint, uint, Vector4*, void> Component_SetVec4;
        public delegate* unmanaged<uint, uint, uint, Vector4*, void> Component_GetQuat;
        public delegate* unmanaged<uint, uint, uint, Vector4*, void> Component_SetQuat;
        public delegate* unmanaged<uint, uint, uint, byte*, int, int> Component_GetString;
        public delegate* unmanaged<uint, uint, uint, GkStr, void> Component_SetString;
    }

    /// <summary>Number of bindings in the table, checked against the native side.</summary>
    public static class EngineApiInfo
    {
        public const int EntryCount = 110;
    }
}

namespace GkNext
{
    public static unsafe class Log
    {
        public static void Info(string message)
        {
            var mark = Utf8Arena.Mark();
            try
            {
                Api.Table->Log_Info(Utf8Arena.Encode(message));
            }
            finally
            {
                Utf8Arena.Release(mark);
            }
        }

        public static void Warn(string message)
        {
            var mark = Utf8Arena.Mark();
            try
            {
                Api.Table->Log_Warn(Utf8Arena.Encode(message));
            }
            finally
            {
                Utf8Arena.Release(mark);
            }
        }

        public static void Error(string message)
        {
            var mark = Utf8Arena.Mark();
            try
            {
                Api.Table->Log_Error(Utf8Arena.Encode(message));
            }
            finally
            {
                Utf8Arena.Release(mark);
            }
        }
    }

    public static unsafe class Engine
    {
        public static uint GetTotalFrames()
        {
            return Api.Table->Engine_GetTotalFrames();
        }

        public static double GetTime()
        {
            return Api.Table->Engine_GetTime();
        }

        public static double GetDeltaSeconds()
        {
            return Api.Table->Engine_GetDeltaSeconds();
        }

        public static double GetSmoothDeltaSeconds()
        {
            return Api.Table->Engine_GetSmoothDeltaSeconds();
        }

        public static void RequestLoadScene(string filename)
        {
            var mark = Utf8Arena.Mark();
            try
            {
                Api.Table->Engine_RequestLoadScene(Utf8Arena.Encode(filename));
            }
            finally
            {
                Utf8Arena.Release(mark);
            }
        }

        public static void RequestClose()
        {
            Api.Table->Engine_RequestClose();
        }

        public static bool IsReplayMode()
        {
            return Api.Table->Engine_IsReplayMode() != 0;
        }
    }

    public static unsafe class Input
    {
        public static bool IsKeyDown(string name)
        {
            var mark = Utf8Arena.Mark();
            try
            {
                return Api.Table->Input_IsKeyDown(Utf8Arena.Encode(name)) != 0;
            }
            finally
            {
                Utf8Arena.Release(mark);
            }
        }

        public static bool IsKeyPressed(string name)
        {
            var mark = Utf8Arena.Mark();
            try
            {
                return Api.Table->Input_IsKeyPressed(Utf8Arena.Encode(name)) != 0;
            }
            finally
            {
                Utf8Arena.Release(mark);
            }
        }

        public static bool IsMouseButtonDown(int button)
        {
            return Api.Table->Input_IsMouseButtonDown(button) != 0;
        }

        public static bool IsMouseButtonPressed(int button)
        {
            return Api.Table->Input_IsMouseButtonPressed(button) != 0;
        }

        public static bool IsGamepadButtonDown(string name)
        {
            var mark = Utf8Arena.Mark();
            try
            {
                return Api.Table->Input_IsGamepadButtonDown(Utf8Arena.Encode(name)) != 0;
            }
            finally
            {
                Utf8Arena.Release(mark);
            }
        }

        public static Vector2 GetMousePosition()
        {
            Vector2 result = default;
            Api.Table->Input_GetMousePosition(&result);
            return result;
        }

        public static float GetGamepadAxis(int axis)
        {
            return Api.Table->Input_GetGamepadAxis(axis);
        }
    }

    public static unsafe class Audio
    {
        public static void PlaySfx(string path, float volume = 1.0f)
        {
            var mark = Utf8Arena.Mark();
            try
            {
                Api.Table->Audio_PlaySfx(Utf8Arena.Encode(path), volume);
            }
            finally
            {
                Utf8Arena.Release(mark);
            }
        }

        public static void PlaySfxEx(string path, float volume, uint minIntervalMs)
        {
            var mark = Utf8Arena.Mark();
            try
            {
                Api.Table->Audio_PlaySfxEx(Utf8Arena.Encode(path), volume, minIntervalMs);
            }
            finally
            {
                Utf8Arena.Release(mark);
            }
        }

        public static void PlayMusic(string path, float volume = 1.0f)
        {
            var mark = Utf8Arena.Mark();
            try
            {
                Api.Table->Audio_PlayMusic(Utf8Arena.Encode(path), volume);
            }
            finally
            {
                Utf8Arena.Release(mark);
            }
        }

        public static void StopMusic()
        {
            Api.Table->Audio_StopMusic();
        }

        public static void SetMusicVolume(float volume)
        {
            Api.Table->Audio_SetMusicVolume(volume);
        }
    }

    public static unsafe class Physics
    {
        public static bool IsAvailable()
        {
            return Api.Table->Physics_IsAvailable() != 0;
        }

        public static void SetWorldPaused(bool paused)
        {
            Api.Table->Physics_SetWorldPaused(paused ? 1 : 0);
        }

        public static bool IsWorldPaused()
        {
            return Api.Table->Physics_IsWorldPaused() != 0;
        }

        public static uint CreateSphereBody(in Vector3 position, float radius, PhysicsMotionType motionType)
        {
            fixed (Vector3* p_position = &position)
            {
                return Api.Table->Physics_CreateSphereBody(p_position, radius, motionType);
            }
        }

        public static uint CreateBoxBody(in Vector3 position, in Vector4 rotation, in Vector3 extent, PhysicsMotionType motionType)
        {
            fixed (Vector3* p_position = &position)
            {
                fixed (Vector4* p_rotation = &rotation)
                {
                    fixed (Vector3* p_extent = &extent)
                    {
                        return Api.Table->Physics_CreateBoxBody(p_position, p_rotation, p_extent, motionType);
                    }
                }
            }
        }

        public static void RemoveBody(uint bodyId)
        {
            Api.Table->Physics_RemoveBody(bodyId);
        }

        public static void SetBodyActive(uint bodyId, bool active)
        {
            Api.Table->Physics_SetBodyActive(bodyId, active ? 1 : 0);
        }

        public static void SetBodyTransform(uint bodyId, in Vector3 position, in Vector4 rotation, bool resetVelocity = false)
        {
            fixed (Vector3* p_position = &position)
            {
                fixed (Vector4* p_rotation = &rotation)
                {
                    Api.Table->Physics_SetBodyTransform(bodyId, p_position, p_rotation, resetVelocity ? 1 : 0);
                }
            }
        }

        public static void MoveKinematicBody(uint bodyId, in Vector3 position, in Vector4 rotation, float deltaSeconds)
        {
            fixed (Vector3* p_position = &position)
            {
                fixed (Vector4* p_rotation = &rotation)
                {
                    Api.Table->Physics_MoveKinematicBody(bodyId, p_position, p_rotation, deltaSeconds);
                }
            }
        }

        public static void SetBodyVelocity(uint bodyId, in Vector3 linearVelocity, in Vector3 angularVelocity)
        {
            fixed (Vector3* p_linearVelocity = &linearVelocity)
            {
                fixed (Vector3* p_angularVelocity = &angularVelocity)
                {
                    Api.Table->Physics_SetBodyVelocity(bodyId, p_linearVelocity, p_angularVelocity);
                }
            }
        }

        public static void AddForceToBody(uint bodyId, in Vector3 force)
        {
            fixed (Vector3* p_force = &force)
            {
                Api.Table->Physics_AddForceToBody(bodyId, p_force);
            }
        }

        public static PhysicsBodyState GetBodyState(uint bodyId)
        {
            PhysicsBodyState result = default;
            Api.Table->Physics_GetBodyState(bodyId, &result);
            return result;
        }
    }

    public static unsafe class Rig
    {
        public static bool IsAvailable()
        {
            return Api.Table->Rig_IsAvailable() != 0;
        }

        public static uint DeclarePool(string rigPath, int capacity)
        {
            var mark = Utf8Arena.Mark();
            try
            {
                return Api.Table->Rig_DeclarePool(Utf8Arena.Encode(rigPath), capacity);
            }
            finally
            {
                Utf8Arena.Release(mark);
            }
        }

        public static bool HasClip(uint poolId, string clip)
        {
            var mark = Utf8Arena.Mark();
            try
            {
                return Api.Table->Rig_HasClip(poolId, Utf8Arena.Encode(clip)) != 0;
            }
            finally
            {
                Utf8Arena.Release(mark);
            }
        }

        public static uint Acquire(uint poolId, in Vector3 position, float yawRadians, in Vector3 tint)
        {
            fixed (Vector3* p_position = &position)
            {
                fixed (Vector3* p_tint = &tint)
                {
                    return Api.Table->Rig_Acquire(poolId, p_position, yawRadians, p_tint);
                }
            }
        }

        public static void Release(uint instanceId)
        {
            Api.Table->Rig_Release(instanceId);
        }

        public static bool IsAlive(uint instanceId)
        {
            return Api.Table->Rig_IsAlive(instanceId) != 0;
        }

        public static void SetTransform(uint instanceId, in Vector3 position, float yawRadians)
        {
            fixed (Vector3* p_position = &position)
            {
                Api.Table->Rig_SetTransform(instanceId, p_position, yawRadians);
            }
        }

        public static void SetVisible(uint instanceId, bool visible)
        {
            Api.Table->Rig_SetVisible(instanceId, visible ? 1 : 0);
        }

        public static void PlayClip(uint instanceId, string clip, float fadeSeconds = 0.15f)
        {
            var mark = Utf8Arena.Mark();
            try
            {
                Api.Table->Rig_PlayClip(instanceId, Utf8Arena.Encode(clip), fadeSeconds);
            }
            finally
            {
                Utf8Arena.Release(mark);
            }
        }

        public static void SetPlaySpeed(uint instanceId, float speed)
        {
            Api.Table->Rig_SetPlaySpeed(instanceId, speed);
        }

        public static uint GetRootNodeId(uint instanceId)
        {
            return Api.Table->Rig_GetRootNodeId(instanceId);
        }

        public static uint GetBoneNodeId(uint instanceId, string boneName)
        {
            var mark = Utf8Arena.Mark();
            try
            {
                return Api.Table->Rig_GetBoneNodeId(instanceId, Utf8Arena.Encode(boneName));
            }
            finally
            {
                Utf8Arena.Release(mark);
            }
        }
    }

    public static unsafe class UI
    {
        public static bool Begin(string name, int flags = 0)
        {
            var mark = Utf8Arena.Mark();
            try
            {
                return Api.Table->UI_Begin(Utf8Arena.Encode(name), flags) != 0;
            }
            finally
            {
                Utf8Arena.Release(mark);
            }
        }

        public static void End()
        {
            Api.Table->UI_End();
        }

        public static void Text(string text)
        {
            var mark = Utf8Arena.Mark();
            try
            {
                Api.Table->UI_Text(Utf8Arena.Encode(text));
            }
            finally
            {
                Utf8Arena.Release(mark);
            }
        }

        public static void SetCursorPos(float x, float y)
        {
            Api.Table->UI_SetCursorPos(x, y);
        }

        public static Vector2 GetWindowSize()
        {
            Vector2 result = default;
            Api.Table->UI_GetWindowSize(&result);
            return result;
        }

        public static void SetWindowFontScale(float scale)
        {
            Api.Table->UI_SetWindowFontScale(scale);
        }

        public static Vector2 GetScreenSize()
        {
            Vector2 result = default;
            Api.Table->UI_GetScreenSize(&result);
            return result;
        }

        public static Vector2 CalcTextSize(string text, float scale = 1.0f)
        {
            var mark = Utf8Arena.Mark();
            try
            {
                Vector2 result = default;
                Api.Table->UI_CalcTextSize(Utf8Arena.Encode(text), scale, &result);
                return result;
            }
            finally
            {
                Utf8Arena.Release(mark);
            }
        }

        public static void DrawText(string text, float x, float y, Color color, float scale = 1.0f)
        {
            var mark = Utf8Arena.Mark();
            try
            {
                Api.Table->UI_DrawText(Utf8Arena.Encode(text), x, y, color.ToPacked(), scale);
            }
            finally
            {
                Utf8Arena.Release(mark);
            }
        }

        public static void DrawRectFilled(float x, float y, float width, float height, Color color, float rounding = 0.0f)
        {
            Api.Table->UI_DrawRectFilled(x, y, width, height, color.ToPacked(), rounding);
        }

        public static void DrawRect(float x, float y, float width, float height, Color color, float rounding = 0.0f, float thickness = 1.0f)
        {
            Api.Table->UI_DrawRect(x, y, width, height, color.ToPacked(), rounding, thickness);
        }

        public static UiTexture RequestTexture(string path, bool srgb = true, bool persistent = true)
        {
            var mark = Utf8Arena.Mark();
            try
            {
                UiTexture result = default;
                Api.Table->UI_RequestTexture(Utf8Arena.Encode(path), srgb ? 1 : 0, persistent ? 1 : 0, &result);
                return result;
            }
            finally
            {
                Utf8Arena.Release(mark);
            }
        }

        public static void SubmitDrawList(System.ReadOnlySpan<UiDrawCommand> commands, System.ReadOnlySpan<Vector2> points, System.ReadOnlySpan<byte> utf8)
        {
            fixed (UiDrawCommand* p_commands = commands)
            {
                fixed (Vector2* p_points = points)
                {
                    fixed (byte* p_utf8 = utf8)
                    {
                        Api.Table->UI_SubmitDrawList(p_commands, commands.Length, p_points, points.Length, p_utf8, utf8.Length);
                    }
                }
            }
        }
    }

    public static unsafe class Scene
    {
        public static uint GetIndicesCount()
        {
            return Api.Table->Scene_GetIndicesCount();
        }

        public static uint FindNodeIdWithComponent(string componentType)
        {
            var mark = Utf8Arena.Mark();
            try
            {
                return Api.Table->Scene_FindNodeIdWithComponent(Utf8Arena.Encode(componentType));
            }
            finally
            {
                Utf8Arena.Release(mark);
            }
        }

        public static uint AddRenderNode(string name, in RenderNodeSpec spec)
        {
            var mark = Utf8Arena.Mark();
            try
            {
                fixed (RenderNodeSpec* p_spec = &spec)
                {
                    return Api.Table->Scene_AddRenderNode(Utf8Arena.Encode(name), p_spec);
                }
            }
            finally
            {
                Utf8Arena.Release(mark);
            }
        }

        public static void RemoveNodeById(uint nodeId)
        {
            Api.Table->Scene_RemoveNodeById(nodeId);
        }

        public static void MarkTransformDirty()
        {
            Api.Table->Scene_MarkTransformDirty();
        }

        public static void RecalcNodeTransform(uint nodeId, bool full = false)
        {
            Api.Table->Scene_RecalcNodeTransform(nodeId, full ? 1 : 0);
        }

        public static void SetNodeTranslation(uint nodeId, in Vector3 translation)
        {
            fixed (Vector3* p_translation = &translation)
            {
                Api.Table->Scene_SetNodeTranslation(nodeId, p_translation);
            }
        }

        public static void SetNodeRotation(uint nodeId, in Vector4 rotation)
        {
            fixed (Vector4* p_rotation = &rotation)
            {
                Api.Table->Scene_SetNodeRotation(nodeId, p_rotation);
            }
        }

        public static void SetNodeScale(uint nodeId, in Vector3 scale)
        {
            fixed (Vector3* p_scale = &scale)
            {
                Api.Table->Scene_SetNodeScale(nodeId, p_scale);
            }
        }

        public static void SetNodeTransform(in NodeTransform transform)
        {
            fixed (NodeTransform* p_transform = &transform)
            {
                Api.Table->Scene_SetNodeTransform(p_transform);
            }
        }

        public static void SetNodeTransforms(System.ReadOnlySpan<NodeTransform> transforms)
        {
            fixed (NodeTransform* p_transforms = transforms)
            {
                Api.Table->Scene_SetNodeTransforms(p_transforms, transforms.Length);
            }
        }

        public static void SetNodeVisible(uint nodeId, bool visible)
        {
            Api.Table->Scene_SetNodeVisible(nodeId, visible ? 1 : 0);
        }

        public static void SetNodeVisibleRecursive(uint nodeId, bool visible)
        {
            Api.Table->Scene_SetNodeVisibleRecursive(nodeId, visible ? 1 : 0);
        }

        public static bool SetNodeParent(uint childId, uint parentId)
        {
            return Api.Table->Scene_SetNodeParent(childId, parentId) != 0;
        }

        public static void SetNodePrimaryMaterial(uint nodeId, uint materialId)
        {
            Api.Table->Scene_SetNodePrimaryMaterial(nodeId, materialId);
        }

        public static void SetNodeMaterialRecursive(uint nodeId, uint materialId)
        {
            Api.Table->Scene_SetNodeMaterialRecursive(nodeId, materialId);
        }

        public static void SetNodeOutlineFlags(uint nodeId, uint outlineFlags)
        {
            Api.Table->Scene_SetNodeOutlineFlags(nodeId, outlineFlags);
        }

        public static uint AddLambertianMaterial(in Vector3 color)
        {
            fixed (Vector3* p_color = &color)
            {
                return Api.Table->Scene_AddLambertianMaterial(p_color);
            }
        }

        public static uint AddDiffuseLightMaterial(in Vector3 color, float intensity = 1.0f)
        {
            fixed (Vector3* p_color = &color)
            {
                return Api.Table->Scene_AddDiffuseLightMaterial(p_color, intensity);
            }
        }

        public static bool BindPhysicsBody(uint nodeId, uint bodyId, NodeMobility mobility)
        {
            return Api.Table->Scene_BindPhysicsBody(nodeId, bodyId, mobility) != 0;
        }

        public static uint GetEnvironmentNodeId()
        {
            return Api.Table->Scene_GetEnvironmentNodeId();
        }
    }

    public static unsafe class SceneBuild
    {
        public static uint AddBoxModel(in Vector3 min, in Vector3 max)
        {
            fixed (Vector3* p_min = &min)
            {
                fixed (Vector3* p_max = &max)
                {
                    return Api.Table->SceneBuild_AddBoxModel(p_min, p_max);
                }
            }
        }

        public static uint AddSphereModel(in Vector3 center, float radius)
        {
            fixed (Vector3* p_center = &center)
            {
                return Api.Table->SceneBuild_AddSphereModel(p_center, radius);
            }
        }

        public static uint AddLambertianMaterial(in Vector3 color)
        {
            fixed (Vector3* p_color = &color)
            {
                return Api.Table->SceneBuild_AddLambertianMaterial(p_color);
            }
        }

        public static uint AddDiffuseLightMaterial(in Vector3 color, float intensity = 1.0f)
        {
            fixed (Vector3* p_color = &color)
            {
                return Api.Table->SceneBuild_AddDiffuseLightMaterial(p_color, intensity);
            }
        }

        public static uint AddRenderNode(string name, in RenderNodeSpec spec)
        {
            var mark = Utf8Arena.Mark();
            try
            {
                fixed (RenderNodeSpec* p_spec = &spec)
                {
                    return Api.Table->SceneBuild_AddRenderNode(Utf8Arena.Encode(name), p_spec);
                }
            }
            finally
            {
                Utf8Arena.Release(mark);
            }
        }

        public static bool BindPhysicsBody(uint nodeId, uint bodyId, NodeMobility mobility)
        {
            return Api.Table->SceneBuild_BindPhysicsBody(nodeId, bodyId, mobility) != 0;
        }
    }

    public static unsafe class Paths
    {
        public static string GetProjectRoot()
        {
            int required = Api.Table->Paths_GetProjectRoot(null, 0);
            if (required <= 0)
            {
                return string.Empty;
            }
            byte[] buffer = new byte[required];
            fixed (byte* bufferPtr = buffer)
            {
                int written = Api.Table->Paths_GetProjectRoot(bufferPtr, required);
                return written <= 0 ? string.Empty : System.Text.Encoding.UTF8.GetString(bufferPtr, written);
            }
        }

        public static string GetOutputDir()
        {
            int required = Api.Table->Paths_GetOutputDir(null, 0);
            if (required <= 0)
            {
                return string.Empty;
            }
            byte[] buffer = new byte[required];
            fixed (byte* bufferPtr = buffer)
            {
                int written = Api.Table->Paths_GetOutputDir(bufferPtr, required);
                return written <= 0 ? string.Empty : System.Text.Encoding.UTF8.GetString(bufferPtr, written);
            }
        }
    }

    public static unsafe class Assets
    {
        public static byte[] ReadFile(string path)
        {
            var mark = Utf8Arena.Mark();
            try
            {
                int required = Api.Table->Assets_ReadFile(Utf8Arena.Encode(path), null, 0);
                if (required <= 0)
                {
                    return System.Array.Empty<byte>();
                }
                byte[] buffer = new byte[required];
                fixed (byte* bufferPtr = buffer)
                {
                    int written = Api.Table->Assets_ReadFile(Utf8Arena.Encode(path), bufferPtr, required);
                    if (written == required)
                    {
                        return buffer;
                    }
                    return written <= 0 ? System.Array.Empty<byte>() : buffer.AsSpan(0, written).ToArray();
                }
            }
            finally
            {
                Utf8Arena.Release(mark);
            }
        }
    }

    public static unsafe class Component
    {
        public static bool Has(uint nodeId, uint typeId)
        {
            return Api.Table->Component_Has(nodeId, typeId) != 0;
        }

        public static bool GetBool(uint nodeId, uint typeId, uint propId)
        {
            return Api.Table->Component_GetBool(nodeId, typeId, propId) != 0;
        }

        public static void SetBool(uint nodeId, uint typeId, uint propId, bool value)
        {
            Api.Table->Component_SetBool(nodeId, typeId, propId, value ? 1 : 0);
        }

        public static int GetInt32(uint nodeId, uint typeId, uint propId)
        {
            return Api.Table->Component_GetInt32(nodeId, typeId, propId);
        }

        public static void SetInt32(uint nodeId, uint typeId, uint propId, int value)
        {
            Api.Table->Component_SetInt32(nodeId, typeId, propId, value);
        }

        public static uint GetUInt32(uint nodeId, uint typeId, uint propId)
        {
            return Api.Table->Component_GetUInt32(nodeId, typeId, propId);
        }

        public static void SetUInt32(uint nodeId, uint typeId, uint propId, uint value)
        {
            Api.Table->Component_SetUInt32(nodeId, typeId, propId, value);
        }

        public static float GetFloat(uint nodeId, uint typeId, uint propId)
        {
            return Api.Table->Component_GetFloat(nodeId, typeId, propId);
        }

        public static void SetFloat(uint nodeId, uint typeId, uint propId, float value)
        {
            Api.Table->Component_SetFloat(nodeId, typeId, propId, value);
        }

        public static double GetDouble(uint nodeId, uint typeId, uint propId)
        {
            return Api.Table->Component_GetDouble(nodeId, typeId, propId);
        }

        public static void SetDouble(uint nodeId, uint typeId, uint propId, double value)
        {
            Api.Table->Component_SetDouble(nodeId, typeId, propId, value);
        }

        public static Vector2 GetVec2(uint nodeId, uint typeId, uint propId)
        {
            Vector2 result = default;
            Api.Table->Component_GetVec2(nodeId, typeId, propId, &result);
            return result;
        }

        public static void SetVec2(uint nodeId, uint typeId, uint propId, in Vector2 value)
        {
            fixed (Vector2* p_value = &value)
            {
                Api.Table->Component_SetVec2(nodeId, typeId, propId, p_value);
            }
        }

        public static Vector3 GetVec3(uint nodeId, uint typeId, uint propId)
        {
            Vector3 result = default;
            Api.Table->Component_GetVec3(nodeId, typeId, propId, &result);
            return result;
        }

        public static void SetVec3(uint nodeId, uint typeId, uint propId, in Vector3 value)
        {
            fixed (Vector3* p_value = &value)
            {
                Api.Table->Component_SetVec3(nodeId, typeId, propId, p_value);
            }
        }

        public static Vector4 GetVec4(uint nodeId, uint typeId, uint propId)
        {
            Vector4 result = default;
            Api.Table->Component_GetVec4(nodeId, typeId, propId, &result);
            return result;
        }

        public static void SetVec4(uint nodeId, uint typeId, uint propId, in Vector4 value)
        {
            fixed (Vector4* p_value = &value)
            {
                Api.Table->Component_SetVec4(nodeId, typeId, propId, p_value);
            }
        }

        public static Vector4 GetQuat(uint nodeId, uint typeId, uint propId)
        {
            Vector4 result = default;
            Api.Table->Component_GetQuat(nodeId, typeId, propId, &result);
            return result;
        }

        public static void SetQuat(uint nodeId, uint typeId, uint propId, in Vector4 value)
        {
            fixed (Vector4* p_value = &value)
            {
                Api.Table->Component_SetQuat(nodeId, typeId, propId, p_value);
            }
        }

        public static string GetString(uint nodeId, uint typeId, uint propId)
        {
            int required = Api.Table->Component_GetString(nodeId, typeId, propId, null, 0);
            if (required <= 0)
            {
                return string.Empty;
            }
            byte[] buffer = new byte[required];
            fixed (byte* bufferPtr = buffer)
            {
                int written = Api.Table->Component_GetString(nodeId, typeId, propId, bufferPtr, required);
                return written <= 0 ? string.Empty : System.Text.Encoding.UTF8.GetString(bufferPtr, written);
            }
        }

        public static void SetString(uint nodeId, uint typeId, uint propId, string value)
        {
            var mark = Utf8Arena.Mark();
            try
            {
                Api.Table->Component_SetString(nodeId, typeId, propId, Utf8Arena.Encode(value));
            }
            finally
            {
                Utf8Arena.Release(mark);
            }
        }
    }
}
