using System.Collections.Immutable;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace GkNext.SourceGen;

/// <summary>
/// Emits <c>GkNext.Generated.GameEntry.Create()</c> for the type marked <c>[GameInstance]</c>.
/// </summary>
/// <remarks>
/// The host resolves this one fixed type name — by reflection under CoreCLR, by a direct call
/// under NativeAOT. Generating it means the entry point is a compile-time fact in both cases, and
/// a game assembly with no entry (or two) fails the build rather than failing to start.
/// </remarks>
[Generator]
public sealed class GameInstanceRegistryGenerator : IIncrementalGenerator
{
    private const string AttributeName = "GkNext.GameInstanceAttribute";

    private static readonly DiagnosticDescriptor DuplicateEntry = new(
        id: "GKNEXT002",
        title: "More than one [GameInstance] type",
        messageFormat: "'{0}' is a second [GameInstance] type; a game assembly must declare exactly one",
        category: "GkNext",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor NotAGameModule = new(
        id: "GKNEXT003",
        title: "[GameInstance] type does not implement IGameModule",
        messageFormat: "'{0}' is marked [GameInstance] but does not implement GkNext.IGameModule (deriving from NextGameInstance is the usual way)",
        category: "GkNext",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor NotConstructible = new(
        id: "GKNEXT004",
        title: "[GameInstance] type has no parameterless constructor",
        messageFormat: "'{0}' is marked [GameInstance] but cannot be constructed without arguments",
        category: "GkNext",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<INamedTypeSymbol> candidates = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (syntaxContext, _) => (INamedTypeSymbol)syntaxContext.TargetSymbol);

        context.RegisterSourceOutput(candidates.Collect(), Emit);
    }

    private static void Emit(SourceProductionContext context, ImmutableArray<INamedTypeSymbol> candidates)
    {
        if (candidates.IsDefaultOrEmpty)
        {
            // Not an error: GkNext.Engine itself is compiled with this generator attached and has
            // no game type. Only a warning, and only for assemblies that opted in.
            return;
        }

        INamedTypeSymbol entry = candidates[0];
        foreach (INamedTypeSymbol duplicate in candidates.Skip(1))
        {
            context.ReportDiagnostic(Diagnostic.Create(
                DuplicateEntry, duplicate.Locations.FirstOrDefault(), duplicate.ToDisplayString()));
        }

        if (!ImplementsGameModule(entry))
        {
            context.ReportDiagnostic(Diagnostic.Create(
                NotAGameModule, entry.Locations.FirstOrDefault(), entry.ToDisplayString()));
            return;
        }

        bool constructible = entry.InstanceConstructors.Any(
            constructor => constructor.Parameters.Length == 0 &&
                           constructor.DeclaredAccessibility != Accessibility.Private);
        if (!constructible)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                NotConstructible, entry.Locations.FirstOrDefault(), entry.ToDisplayString()));
            return;
        }

        string typeName = entry.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        string source = $$"""
            // <auto-generated>
            //     Generated by GkNext.SourceGen from the [GameInstance] attribute. Do not edit.
            // </auto-generated>

            namespace GkNext.Generated
            {
                /// <summary>
                /// The fixed handshake the host looks for. Resolved by name under CoreCLR and called
                /// directly under NativeAOT.
                /// </summary>
                public static class GameEntry
                {
                    public static global::GkNext.IGameModule Create() => new {{typeName}}();
                }
            }
            """;

        context.AddSource("GkNext.GameEntry.g.cs", source);
    }

    private static bool ImplementsGameModule(INamedTypeSymbol type)
    {
        return type.AllInterfaces.Any(
            candidate => candidate.ToDisplayString() == "GkNext.IGameModule");
    }
}
