package csharpgen

import (
	"fmt"
	"sort"
	"strings"
)

// ComponentsOutputPath is the generated component wrapper file. Nothing else may write it.
const ComponentsOutputPath = "assets/csharp/GkNext.Engine/Components.g.cs"

// accessor is how one reflected property type crosses the boundary: the managed type, the pair of
// Component_* bindings that carry it, and whether the setter takes the value by reference.
type accessor struct {
	Managed string
	Getter  string
	Setter  string
	ByRef   bool
}

var accessors = map[string]accessor{
	"Bool":   {"bool", "GetBool", "SetBool", false},
	"Int32":  {"int", "GetInt32", "SetInt32", false},
	"UInt32": {"uint", "GetUInt32", "SetUInt32", false},
	"Float":  {"float", "GetFloat", "SetFloat", false},
	"Double": {"double", "GetDouble", "SetDouble", false},
	"String": {"string", "GetString", "SetString", false},
	"Vec2":   {"Vector2", "GetVec2", "SetVec2", true},
	"Vec3":   {"Vector3", "GetVec3", "SetVec3", true},
	"Vec4":   {"Vector4", "GetVec4", "SetVec4", true},
	// glm::quat has no managed counterpart; the binding transports it as (x, y, z, w).
	"Quat": {"Vector4", "GetQuat", "SetQuat", true},
}

// skipReasons covers reflected property types that deliberately have no binding yet. They are
// listed in the generated file rather than dropped, so the gap is visible where someone would look
// for the property instead of appearing to be an oversight.
var skipReasons = map[string]string{
	"Enum":     "enum properties would need generated enum types; the manifest carries only a type id",
	"Array":    "arrays need element-level accessors, not a value copy",
	"Mat4":     "no managed matrix type yet",
	"AssetRef": "asset references have no managed counterpart yet",
	"Unknown":  "the engine could not deduce this property's type",
}

// reservedMembers are the names NodeRef and the component wrappers already define. A reflected
// property that collides with one would generate a file that does not compile, so the generator
// stops with a clear message instead.
var reservedMembers = map[string]bool{
	"Id": true, "TypeId": true, "IsValid": true, "Invalid": true,
	"Has": true, "GetComponent": true, "FromNode": true, "WithComponent": true,
	"ComponentTypeId": true, "ComponentTypeName": true, "Equals": true,
	"GetHashCode": true, "ToString": true, "GetType": true,
}

// csharpKeywords is not the full list — only the ones a property name plausibly collides with.
var csharpKeywords = map[string]bool{
	"base": true, "class": true, "default": true, "delegate": true, "double": true,
	"event": true, "fixed": true, "float": true, "int": true, "lock": true, "new": true,
	"object": true, "operator": true, "out": true, "override": true, "params": true,
	"ref": true, "string": true, "this": true, "true": true, "false": true, "void": true,
}

// GenerateComponents renders Components.g.cs from the reflection manifest.
func GenerateComponents(manifest Manifest) (string, error) {
	var node *ReflectedType
	var components []ReflectedType
	for index := range manifest.Types {
		if manifest.Types[index].IsNode() {
			node = &manifest.Types[index]
			continue
		}
		components = append(components, manifest.Types[index])
	}
	if node == nil {
		return "", fmt.Errorf("%s: no type is marked as the node kind", ManifestPath)
	}

	// Component name -> the shorthand property on NodeRef, e.g. RenderComponent -> Render.
	shorthand := map[string]string{}
	used := map[string]bool{}
	for _, property := range node.Properties {
		used[property.Name] = true
	}
	for _, component := range components {
		name := strings.TrimSuffix(component.Name, "Component")
		if name == "" {
			name = component.Name
		}
		if used[name] || reservedMembers[name] {
			return "", fmt.Errorf("%s: shorthand %q for %s collides with an existing member on NodeRef",
				ManifestPath, name, component.Name)
		}
		used[name] = true
		shorthand[component.Name] = name
	}

	var out strings.Builder
	out.WriteString(`// <auto-generated>
//     Generated by 'gnb csharpgen' from src/Modules/NextDotNet/ReflectionManifest.json.
//     Do not edit. Expose a property by registering it with REFLECT_COMPONENT, refreshing the
//     manifest ('gnb csharpgen --refresh'), and regenerating.
//     'gnb csharpgen --check' fails when this file is out of date.
// </auto-generated>

using GkNext.Interop;

namespace GkNext;

/// <summary>
/// Implemented by every generated component wrapper, so a node can be asked for one by type.
/// </summary>
/// <remarks>
/// Wrappers are readonly structs holding nothing but a node id, which is why
/// <c>node.Render.Visible = false</c> works despite operating on a returned copy: the assignment
/// goes straight through to the engine rather than mutating the struct.
/// </remarks>
public interface IComponentRef<TSelf> where TSelf : struct, IComponentRef<TSelf>
{
    /// <summary>Hash of the name the component is registered under in entt::meta.</summary>
    static abstract uint ComponentTypeId { get; }

    /// <summary>The registered name, for the bindings that address components by string.</summary>
    static abstract string ComponentTypeName { get; }

    static abstract TSelf FromNode(uint nodeId);
}

`)

	if err := emitNode(&out, *node, components, shorthand); err != nil {
		return "", err
	}
	for _, component := range components {
		out.WriteString("\n")
		if err := emitComponent(&out, component); err != nil {
			return "", err
		}
	}
	return out.String(), nil
}

func emitNode(out *strings.Builder, node ReflectedType, components []ReflectedType, shorthand map[string]string) error {
	fmt.Fprintf(out, `/// <summary>A handle to a scene node: its own reflected properties, plus its components.</summary>
/// <remarks>
/// Holds only an id, so it stays valid across frames but says nothing about whether the node still
/// exists. Node ids are only addressable once the scene is committed — inside
/// <c>BeforeSceneRebuild</c> a node's starting state belongs in the spec it is created with.
/// </remarks>
public readonly struct NodeRef(uint nodeId)
{
    public readonly uint Id = nodeId;

    /// <summary>Hash of "%s" in entt::meta.</summary>
    public const uint TypeId = %du;

    public static NodeRef Invalid => new(NodeIds.Invalid);

    public bool IsValid => NodeIds.IsValid(Id);

    /// <summary>The first node in the committed scene carrying <typeparamref name="T"/>.</summary>
    public static NodeRef WithComponent<T>() where T : struct, IComponentRef<T>
        => new(Scene.FindNodeIdWithComponent(T.ComponentTypeName));

    public bool Has<T>() where T : struct, IComponentRef<T> => Component.Has(Id, T.ComponentTypeId);

    public T GetComponent<T>() where T : struct, IComponentRef<T> => T.FromNode(Id);
`, node.Name, node.TypeID)

	if err := emitProperties(out, node.Properties, "TypeId"); err != nil {
		return err
	}

	out.WriteString("\n    // Shorthand for the components registered with the engine.\n")
	for _, component := range components {
		fmt.Fprintf(out, "    public %s %s => new(Id);\n", component.Name, shorthand[component.Name])
	}
	out.WriteString("}\n")
	return nil
}

func emitComponent(out *strings.Builder, component ReflectedType) error {
	fmt.Fprintf(out, `public readonly struct %s(uint nodeId) : IComponentRef<%s>
{
    public readonly uint Id = nodeId;

    /// <summary>Hash of "%s" in entt::meta.</summary>
    public const uint TypeId = %du;

    static uint IComponentRef<%s>.ComponentTypeId => TypeId;

    static string IComponentRef<%s>.ComponentTypeName => "%s";

    static %s IComponentRef<%s>.FromNode(uint nodeId) => new(nodeId);

    /// <summary>Whether the node this handle came from actually carries this component.</summary>
    public bool Exists => Component.Has(Id, TypeId);
`, component.Name, component.Name,
		component.Name, component.TypeID,
		component.Name,
		component.Name, component.Name,
		component.Name, component.Name)

	if err := emitProperties(out, component.Properties, "TypeId"); err != nil {
		return err
	}
	out.WriteString("}\n")
	return nil
}

func emitProperties(out *strings.Builder, properties []ReflectedProperty, typeIDExpr string) error {
	var skipped []string
	for _, property := range properties {
		if !property.ScriptExposed {
			skipped = append(skipped, fmt.Sprintf("%s — not script-exposed", property.Name))
			continue
		}

		mapped, ok := accessors[property.Type]
		if !ok {
			reason, known := skipReasons[property.Type]
			if !known {
				return fmt.Errorf("property %s has unhandled type %q; add it to accessors or skipReasons",
					property.Name, property.Type)
			}
			skipped = append(skipped, fmt.Sprintf("%s (%s) — %s", property.Name, property.Type, reason))
			continue
		}

		name := property.Name
		if reservedMembers[name] {
			return fmt.Errorf("property %s collides with a member the generator already defines", name)
		}
		if csharpKeywords[name] {
			name = "@" + name
		}

		out.WriteString("\n")
		writeDoc(out, property)
		getter := fmt.Sprintf("Component.%s(Id, %s, %du)", mapped.Getter, typeIDExpr, property.PropID)
		if property.ReadOnly {
			fmt.Fprintf(out, "    public %s %s => %s;\n", mapped.Managed, name, getter)
			continue
		}

		argument := "value"
		if mapped.ByRef {
			argument = "in value"
		}
		fmt.Fprintf(out, "    public %s %s\n    {\n        get => %s;\n        set => Component.%s(Id, %s, %du, %s);\n    }\n",
			mapped.Managed, name, getter, mapped.Setter, typeIDExpr, property.PropID, argument)
	}

	if len(skipped) > 0 {
		sort.Strings(skipped)
		out.WriteString("\n    // Reflected but not bound:\n")
		for _, entry := range skipped {
			fmt.Fprintf(out, "    //   %s\n", entry)
		}
	}
	return nil
}

func writeDoc(out *strings.Builder, property ReflectedProperty) {
	summary := property.Tooltip
	if summary == "" {
		summary = property.DisplayName
	}
	if summary == "" {
		summary = property.Name
	}
	fmt.Fprintf(out, "    /// <summary>%s", escapeXML(summary))
	if property.Category != "" {
		fmt.Fprintf(out, " (%s)", escapeXML(property.Category))
	}
	if property.ReadOnly {
		out.WriteString(" Read-only.")
	}
	out.WriteString("</summary>\n")
}

func escapeXML(text string) string {
	replacer := strings.NewReplacer("&", "&amp;", "<", "&lt;", ">", "&gt;")
	return replacer.Replace(text)
}
