add_subdirectory(MagicaLego)
add_subdirectory(KongLie3D)
add_subdirectory(Brotato3D)
add_subdirectory(NextRA)
add_subdirectory(Flappy)
add_subdirectory(BrickPlayer)
add_subdirectory(CharacterDemo)
add_subdirectory(NextDayz)
add_subdirectory(TruckerDemo)
add_subdirectory(StudioSim)
add_subdirectory(AirportSim)
add_subdirectory(CitySolSim)
add_subdirectory(Voyage3D)
add_subdirectory(NextTotalwar)
if(GK_DOTNET_ENABLED)
    add_subdirectory(DotNetSandbox)
endif()
