// generated by ScadLibrary scene assembly
// This flat placement format can be reopened in the Scene Assembly object editor.
$fn = 12;
use <../lib/kit_old_city.scad>
use <../lib/kit_city_hd.scad>

color([0.50, 0.51, 0.53]) translate([0, 0, -0.15]) cube([80.0, 80.0, 0.3], center = true);

translate([-14.00, 8.00, 0]) rotate([0, 0, 12]) scale([1.000, 1.000, 1.000]) oc_bldg_house(seed = 3);
translate([12.00, 9.00, 0]) rotate([0, 0, -18]) scale([1.000, 1.000, 1.000]) oc_bldg_house(seed = 7);
translate([0.00, -8.00, 0]) rotate([0, 0, 0]) scale([1.000, 1.000, 1.000]) oc_prop_well();
translate([-9.00, -15.00, 0]) rotate([0, 0, 0]) scale([1.100, 1.100, 1.100]) hc_nature_tree(1.0, 4);
translate([10.00, -15.00, 0]) rotate([0, 0, 0]) scale([1.200, 1.200, 1.200]) oc_nature_pine(1.0);
