message(STATUS "SDL3_DIR: ${SDL3_DIR}")
find_package(SDL3 CONFIG REQUIRED)

include(${CMAKE_CURRENT_LIST_DIR}/SetupVulkan.cmake)

if(NOT IOS AND NOT ANDROID)
    find_package(cpptrace CONFIG REQUIRED)
endif()

find_package(glm CONFIG REQUIRED)
find_package(imgui CONFIG REQUIRED)
find_package(Stb REQUIRED)
if(NOT IOS)
    find_package(CURL REQUIRED)
endif()
find_package(Ktx CONFIG REQUIRED)
find_package(meshoptimizer CONFIG REQUIRED)
find_package(fmt CONFIG REQUIRED)
find_package(xxHash CONFIG REQUIRED)
find_package(spdlog REQUIRED)
find_package(draco CONFIG REQUIRED)

if(GK_ENABLE_TRACY AND NOT IOS)
    find_package(Tracy CONFIG QUIET)
    if(NOT TARGET Tracy::TracyClient)
        message(STATUS "Tracy package not found; disabling GK_ENABLE_TRACY")
        set(GK_ENABLE_TRACY OFF CACHE BOOL "Enable Tracy CPU/GPU profiling client" FORCE)
    else()
        message(STATUS "Tracy profiling client enabled")
    endif()
endif()

if(WITH_AVIF)
    find_package(libavif CONFIG REQUIRED)
endif()

find_path(TINYGLTF_INCLUDE_DIRS "tiny_gltf.h" REQUIRED)
find_path(CPP_BASE64_INCLUDE_DIRS "cpp-base64/base64.cpp" REQUIRED)

set(WITH_SUPERLUMINAL OFF)
set(GK_SUPERLUMINAL_API_DIR "C:/Program Files/Superluminal/Performance/API")
if(WIN32 AND EXISTS "${GK_SUPERLUMINAL_API_DIR}")
    set(WITH_SUPERLUMINAL ON)
    set(SuperluminalAPI_ROOT "${GK_SUPERLUMINAL_API_DIR}")
    set(SuperluminalAPI_USE_STATIC_RUNTIME 1)
    list(APPEND CMAKE_MODULE_PATH "${GK_SUPERLUMINAL_API_DIR}")
    find_package(SuperluminalAPI REQUIRED)
    message(STATUS "Superluminal Performance API enabled: ${GK_SUPERLUMINAL_API_DIR}")
else()
    message(STATUS "Superluminal Performance API disabled")
endif()

set(WITH_RENDERDOC OFF)
set(GK_RENDERDOC_API_DIR "C:/Program Files/RenderDoc")
set(GK_RENDERDOC_ANDROID OFF)
if(EXISTS "${GK_RENDERDOC_API_DIR}/renderdoc_app.h" AND (WIN32 OR (ANDROID AND CMAKE_HOST_WIN32)))
    set(WITH_RENDERDOC ON)
    if(WIN32)
        file(TO_CMAKE_PATH "${GK_RENDERDOC_API_DIR}/renderdoc.dll" GK_RENDERDOC_DLL_PATH)
    elseif(ANDROID)
        set(GK_RENDERDOC_ANDROID ON)
    endif()
    message(STATUS "RenderDoc integration enabled: ${GK_RENDERDOC_API_DIR}")
else()
    message(STATUS "RenderDoc integration disabled")
endif()
