package visualstudio

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"sort"
	"strings"

	"github.com/gameknife/gknextrenderer/tools/gnb/internal/console"
)

const solutionPreset = "windows-vcproj"

// SolutionPath returns the solution generated by the Visual Studio preset.
func SolutionPath(repoRoot string) (string, error) {
	buildDir := filepath.Join(repoRoot, "out", "build", solutionPreset)
	preferred := []string{
		filepath.Join(buildDir, "gkNextRenderer.slnx"),
		filepath.Join(buildDir, "gkNextRenderer.sln"),
	}
	for _, path := range preferred {
		if _, err := os.Stat(path); err == nil {
			return path, nil
		}
	}

	var matches []string
	_ = filepath.WalkDir(buildDir, func(path string, entry os.DirEntry, err error) error {
		if err != nil || entry.IsDir() {
			return nil
		}
		extension := strings.ToLower(filepath.Ext(entry.Name()))
		if extension == ".sln" || extension == ".slnx" {
			matches = append(matches, path)
		}
		return nil
	})
	if len(matches) == 0 {
		return "", fmt.Errorf("Visual Studio solution was not generated under %s", buildDir)
	}
	sort.Strings(matches)
	return matches[0], nil
}

// Launch opens a solution in the installed Visual Studio IDE.
func Launch(solutionPath string) (string, error) {
	if runtime.GOOS != "windows" {
		return "", fmt.Errorf("gnb visualstudio is supported only on Windows")
	}
	if _, err := os.Stat(solutionPath); err != nil {
		return "", fmt.Errorf("Visual Studio solution not found: %s: %w", solutionPath, err)
	}

	devenv, err := findDevenv()
	if err != nil {
		return "", err
	}
	console.Command(devenv, solutionPath)
	cmd := exec.Command(devenv, solutionPath)
	cmd.Dir = filepath.Dir(solutionPath)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Start(); err != nil {
		return "", fmt.Errorf("start Visual Studio: %w", err)
	}
	_ = cmd.Process.Release()
	return devenv, nil
}

func findDevenv() (string, error) {
	for _, name := range []string{"devenv.exe", "devenv"} {
		if path, err := exec.LookPath(name); err == nil {
			return path, nil
		}
	}

	if programFilesX86 := os.Getenv("ProgramFiles(x86)"); programFilesX86 != "" {
		vswhere := filepath.Join(programFilesX86, "Microsoft Visual Studio", "Installer", "vswhere.exe")
		if _, err := os.Stat(vswhere); err == nil {
			output, err := exec.Command(vswhere,
				"-latest", "-products", "*",
				"-requires", "Microsoft.VisualStudio.Component.VC.Tools.x86.x64",
				"-find", `Common7\IDE\devenv.exe`).Output()
			if err == nil {
				for _, line := range strings.Split(string(output), "\n") {
					path := strings.TrimSpace(line)
					if path != "" {
						if _, statErr := os.Stat(path); statErr == nil {
							return path, nil
						}
					}
				}
			}
		}
	}

	for _, root := range []string{os.Getenv("ProgramFiles"), os.Getenv("ProgramFiles(x86)")} {
		if root == "" {
			continue
		}
		for _, version := range []string{"18", "17"} {
			for _, edition := range []string{"Community", "Professional", "Enterprise"} {
				pattern := filepath.Join(root, "Microsoft Visual Studio", version, edition, "Common7", "IDE", "devenv.exe")
				if _, err := os.Stat(pattern); err == nil {
					return pattern, nil
				}
			}
		}
	}

	return "", fmt.Errorf("Visual Studio devenv.exe not found; install Visual Studio with the C++ workload")
}
