#include "CharacterDesigner.hpp"

#include "Engine/Assets/Core/Node.hpp"
#include "Engine/Assets/Core/Scene.hpp"
#include "Engine/Assets/Data/Material.hpp"
#include "Engine/Runtime/Scene/SceneBuilder.hpp"
#include "Modules/ScadLoader/FScadRig.h"

#include <fmt/format.h>
#include <spdlog/spdlog.h>

namespace ScadLibrary
{
    namespace
    {
        // True when `params` declares a parameter of exactly this name
        // ("c = ch_HAIRC()" has "c"; "screen = ..." does not have "c").
        bool HasNamedParam(const std::string& params, const std::string& name)
        {
            size_t pos = 0;
            while ((pos = params.find(name, pos)) != std::string::npos)
            {
                const bool startOk = pos == 0 || params[pos - 1] == ' ' || params[pos - 1] == ',';
                const size_t end = pos + name.size();
                const bool endOk = end >= params.size() || params[end] == ' ' || params[end] == '=' ||
                                   params[end] == ',';
                if (startOk && endOk)
                {
                    return true;
                }
                pos = end;
            }
            return false;
        }

        std::string ColorLiteral(const float rgb[3])
        {
            return fmt::format("[{:.2f}, {:.2f}, {:.2f}]", rgb[0], rgb[1], rgb[2]);
        }

        // Part call with the designer's skin (and, for hair, hair color) bound
        // to the module's named parameters; everything else keeps kit defaults
        // so ch_TINT() placeholders stay runtime-tintable.
        std::string PartCall(const FKitModuleInfo& moduleInfo, const float skin[3],
                             const float* hairColor = nullptr)
        {
            std::vector<std::string> args;
            if (hairColor != nullptr && HasNamedParam(moduleInfo.params, "c"))
            {
                args.push_back(fmt::format("c = {}", ColorLiteral(hairColor)));
            }
            if (HasNamedParam(moduleInfo.params, "skin"))
            {
                args.push_back(fmt::format("skin = {}", ColorLiteral(skin)));
            }
            std::string joined;
            for (size_t i = 0; i < args.size(); ++i)
            {
                joined += (i > 0 ? ", " : "") + args[i];
            }
            return fmt::format("{}({})", moduleInfo.name, joined);
        }
    } // namespace

    void FCharacterDesigner::SetKit(const FKitInfo* kit)
    {
        heads_.clear();
        hairs_.clear();
        hats_.clear();
        torsos_.clear();
        arms_.clear();
        legs_.clear();
        accs_.clear();
        hasKit_ = false;
        if (kit != nullptr)
        {
            for (const FKitModuleInfo& moduleInfo : kit->modules)
            {
                if (moduleInfo.category == "head") heads_.push_back(moduleInfo);
                else if (moduleInfo.category == "hair") hairs_.push_back(moduleInfo);
                else if (moduleInfo.category == "hat") hats_.push_back(moduleInfo);
                else if (moduleInfo.category == "torso") torsos_.push_back(moduleInfo);
                else if (moduleInfo.category == "arm") arms_.push_back(moduleInfo);
                else if (moduleInfo.category == "leg") legs_.push_back(moduleInfo);
                else if (moduleInfo.category == "acc") accs_.push_back(moduleInfo);
            }
            hasKit_ = !heads_.empty() && !torsos_.empty() && !arms_.empty() && !legs_.empty();
        }
        head = 0;
        hair = hairs_.empty() ? -1 : 0;
        hat = -1;
        torso = 0;
        arm = 0;
        leg = 0;
        accEnabled.assign(accs_.size(), 0);
    }

    std::string FCharacterDesigner::BuildSource(const std::string& kitUsePath) const
    {
        std::string s;
        s += "// generated by ScadLibrary character designer\n";
        s += "$fn = 8;\n";
        s += fmt::format("use <{}>\n\n", kitUsePath);

        s += "module bone_head()\n{\n";
        s += fmt::format("    {};\n", PartCall(heads_[head], skinColor));
        if (hair >= 0 && hair < static_cast<int>(hairs_.size()))
        {
            s += fmt::format("    {};\n", PartCall(hairs_[hair], skinColor, hairColor));
        }
        if (hat >= 0 && hat < static_cast<int>(hats_.size()))
        {
            s += fmt::format("    {};\n", PartCall(hats_[hat], skinColor));
        }
        s += "}\n\n";

        s += fmt::format("module bone_arm_l() {{ {}; }}\n", PartCall(arms_[arm], skinColor));
        s += fmt::format("module bone_arm_r() {{ mirror([1, 0, 0]) {}; }}\n\n",
                         PartCall(arms_[arm], skinColor));
        s += fmt::format("module bone_leg_l() {{ {}; }}\n", PartCall(legs_[leg], skinColor));
        s += fmt::format("module bone_leg_r() {{ mirror([1, 0, 0]) {}; }}\n\n",
                         PartCall(legs_[leg], skinColor));

        s += "module bone_torso()\n{\n";
        s += fmt::format("    {};\n", PartCall(torsos_[torso], skinColor));
        for (size_t i = 0; i < accs_.size(); ++i)
        {
            if (i < accEnabled.size() && accEnabled[i] != 0)
            {
                s += fmt::format("    {}();\n", accs_[i].name);
            }
        }
        s += "    translate(ch_pivot_head())  bone_head();\n";
        s += "    translate(ch_pivot_arm_l()) bone_arm_l();\n";
        s += "    translate(ch_pivot_arm_r()) bone_arm_r();\n";
        s += "}\n\n";

        s += "module bone_root()\n{\n";
        s += "    translate(ch_pivot_torso()) bone_torso();\n";
        s += "    translate(ch_pivot_leg_l()) bone_leg_l();\n";
        s += "    translate(ch_pivot_leg_r()) bone_leg_r();\n";
        s += "}\n\n";
        s += "bone_root();\n\n";

        s += "anim_idle = ch_clip_idle();\n";
        s += "anim_walk = ch_clip_walk();\n";
        s += "anim_sit  = ch_clip_sit();\n";
        s += "anim_work = ch_clip_work();\n";
        s += "anim_wave = ch_clip_wave();\n";
        return s;
    }

    // ------------------------------------------------------------------ rig preview

    bool FRigPreview::LoadRig(const std::string& scadPathAbs, std::string& outError,
                              std::vector<std::string>* outWarnings)
    {
        hasRig_ = Assets::FScadRigLoader::LoadRig(scadPathAbs, {}, asset_, outError, outWarnings);
        return hasRig_;
    }

    void FRigPreview::SetTint(const glm::vec3& tint)
    {
        tint_ = tint;
        if (scene_ != nullptr && injected_ && tintMaterialId_ < scene_->Materials().size())
        {
            scene_->Materials()[tintMaterialId_].gpuMaterial_.Diffuse = glm::vec4(tint_, 1.0f);
        }
    }

    void FRigPreview::PlayClip(const std::string& clip)
    {
        clip_ = clip;
        if (animatorBound_)
        {
            animator_.Play(!clip_.empty() && asset_.FindClip(clip_) != nullptr ? clip_ : "");
        }
    }

    void FRigPreview::InjectAssets(std::vector<Assets::Model>& models,
                                   std::vector<Assets::FMaterial>& materials)
    {
        if (!active_ || !hasRig_)
        {
            return;
        }
        partModelIds_.clear();
        partMaterialIds_.clear();
        for (const Assets::FRigPart& part : asset_.parts)
        {
            std::array<uint32_t, 16> sectionMaterials = {0};
            for (size_t section = 0;
                 section < part.sectionColors.size() && section < sectionMaterials.size(); ++section)
            {
                if (!part.sectionTintable[section])
                {
                    sectionMaterials[section] = Assets::SceneBuilder::AddLambertianMaterial(
                        materials, glm::vec3(part.sectionColors[section]));
                }
            }
            partMaterialIds_.push_back(sectionMaterials);
            models.push_back(asset_.partModels[part.modelIndex]);
            partModelIds_.push_back(static_cast<uint32_t>(models.size() - 1));
        }
        tintMaterialId_ = Assets::SceneBuilder::AddLambertianMaterial(materials, tint_);
        injected_ = true;
    }

    void FRigPreview::OnSceneLoaded(Assets::Scene& scene)
    {
        if (!active_ || !injected_ || !hasRig_)
        {
            return;
        }
        NextGameplay::FRigInstanceDesc desc;
        desc.namePrefix = "rig_preview";
        desc.partModelIds = partModelIds_;
        desc.partMaterialIds = partMaterialIds_;
        for (size_t partIndex = 0; partIndex < asset_.parts.size(); ++partIndex)
        {
            const Assets::FRigPart& part = asset_.parts[partIndex];
            for (size_t section = 0; section < part.sectionTintable.size() && section < 16; ++section)
            {
                if (part.sectionTintable[section])
                {
                    desc.partMaterialIds[partIndex][section] = tintMaterialId_;
                }
            }
        }

        std::vector<Assets::Node*> boneNodes;
        auto root = NextGameplay::FRigInstance::Instantiate(scene, asset_, desc, boneNodes);
        if (!root)
        {
            SPDLOG_WARN("[ScadLibrary] rig preview instantiation failed");
            return;
        }
        animator_.Bind(&asset_, std::move(boneNodes), root.get());
        animatorBound_ = true;
        scene_ = &scene;
        PlayClip(clip_);
        scene.MarkDirty();
    }

    void FRigPreview::OnSceneUnloaded()
    {
        // Engine order is BeforeSceneRebuild -> OnSceneUnloaded -> OnSceneLoaded:
        // the injection results for the INCOMING scene are already recorded here,
        // so only the dead per-node state may be reset (the AirportSim lesson).
        animator_ = NextGameplay::FRigAnimator{};
        animatorBound_ = false;
        scene_ = nullptr;
    }

    void FRigPreview::Tick(double deltaSeconds)
    {
        if (!active_ || !animatorBound_ || scene_ == nullptr)
        {
            return;
        }
        animator_.Update(static_cast<float>(deltaSeconds));
        scene_->MarkTransformDirty();
    }
}
