#pragma once

#include <string>
#include <vector>

namespace ScadLibrary
{
    // One module signature inside a kit library file.
    struct FKitModuleInfo
    {
        std::string name;     // e.g. "hc_nature_tree"
        std::string params;   // normalized signature, e.g. "s = 1.0, i = 0"
        std::string category; // derived from the name: nature/prop/furn/bldg/veh/...
        int line = 0;         // 1-based line in the kit file

        // Metrics from catalog.json (ScadCatalog tool); absent under text scan.
        bool hasMetrics = false;
        float footprintX = 0.0f; // SCAD-space bbox extents with default args
        float footprintY = 0.0f;
        float height = 0.0f;
        int triangles = 0;
    };

    // One kit_*.scad parts library under assets/scad/lib/.
    struct FKitInfo
    {
        std::string name;       // e.g. "kit_city_hd"
        std::string filePath;   // absolute path
        std::string scaleClass; // city/mid/human (catalog only)
        std::vector<FKitModuleInfo> modules;
    };

    // Scan `libDirAbs` for kit_*.scad files and list their module signatures.
    // Pure text scan (the kit files originated from a one-time mechanical split);
    // modules come back sorted by (category, name) for tree display.
    std::vector<FKitInfo> ScanKits(const std::string& libDirAbs);

    // Load kits from `libDirAbs`/catalog.json (generated by `gnb scad catalog`),
    // including per-module footprint/height metrics. Falls back to ScanKits when
    // the catalog is missing or unreadable; `outFromCatalog` reports which path ran.
    std::vector<FKitInfo> LoadKits(const std::string& libDirAbs, bool& outFromCatalog);
}
