name: Android CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v6
        with:
          go-version: '1.23.x'
      - name: Cache key
        id: gnb
        run: echo "key=$(./gnb.sh info --bincache-key)" >> "$GITHUB_OUTPUT"
      - uses: actions/cache/restore@v6
        id: cache-vcpkg-restore
        with:
          path: |
            .vcpkg
            .vcpkg_bincache
          key: ${{ steps.gnb.outputs.key }}-android
      - run: ./gnb.sh setup --skip-paks
      - run: ./gnb.sh android release
      - uses: actions/cache/save@v6
        if: steps.cache-vcpkg-restore.outputs.cache-hit != 'true'
        with:
          path: |
            .vcpkg
            .vcpkg_bincache
          key: ${{ steps.gnb.outputs.key }}-android
