name: Android CI (Self)

on:
  pull_request:
    branches: [main, dev, 'releases/**']
  push:
    branches: [main, 'releases/**']
    paths:
      - '.github/workflows/**'
      - 'src/**'
      - 'assets/shaders/**'
      - 'tools/gnb/**'
      - 'gnb.*'
      - '**/CMakeLists.txt'

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          clean: false
      - run: .\gnb.bat setup --vcpkg-only
        shell: cmd
      - run: .\gnb.bat android release
        shell: cmd
