name: iOS CI

on:
  pull_request:
    branches:
      - main
      - dev
      - 'releases/**'
  push:
    branches:
      - main
      - 'releases/**'
    paths:
      - '.github/workflows/**'
      - 'src/**'
      - 'assets/shaders/**'
      - '*.sh'
      - '*.bat'
      - '**/CMakeLists.txt'
jobs:
  build:

    runs-on: macos-latest
    env: 
      SDK_VERSION: 1.4.313.1
    steps:
    - uses: actions/checkout@v4
    - name: Install Vulkan SDK
      run: |
        brew install molten-vk
        brew install glslang

    - name: Download and setup slangc
      run: |
        curl -L https://github.com/shader-slang/slang/releases/download/vulkan-sdk-1.4.313.0/slang-vulkan-sdk-1.4.313.0-macos-aarch64.zip -o slang.zip
        mkdir -p slang
        unzip slang.zip -d slang
        echo "$PWD/slang/bin" >> $GITHUB_PATH
        echo "Downloaded and added slangc to PATH"

    - name: Compile vcpkg dependencies
      run: ./vcpkg.sh ios

    - name: Restore cached vcpkg
      id: cache-vcpkg-restore
      uses: actions/cache/restore@v4
      with:
        path: |
          .vcpkg
          .vcpkg_bincache
        key: ${{ runner.os }}-ios-bincache
        
    - name: Compile gkNextRenderer
      run: |
        slangc -v
        ./build.sh ios

    - name: Save vcpkg to cache
      if: github.event_name != 'pull_request'
      id: cache-vcpkg-save
      uses: actions/cache/save@v4
      with:
        path: |
          .vcpkg
          .vcpkg_bincache
        key: ${{ steps.cache-vcpkg-restore.outputs.cache-primary-key }}


