name: MacOS CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
      - name: Cache key
        id: gnb
        run: echo "key=$(./gnb.sh info --bincache-key)" >> "$GITHUB_OUTPUT"
      - uses: actions/cache/restore@v4
        id: cache-vcpkg-restore
        with:
          path: |
            .vcpkg
            .vcpkg_bincache
          key: ${{ steps.gnb.outputs.key }}
      - run: ./gnb.sh setup
      - run: ./gnb.sh build
      - uses: actions/cache/save@v4
        if: steps.cache-vcpkg-restore.outputs.cache-hit != 'true'
        with:
          path: |
            .vcpkg
            .vcpkg_bincache
          key: ${{ steps.gnb.outputs.key }}
