name: Release MagicaLego

on:
  push:
    tags:
      - 'm*'

jobs:
  make-release:
    runs-on: ubuntu-22.04
    outputs:
      uploadurl: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v4
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  windows-build:
    needs: make-release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
      - uses: microsoft/setup-msbuild@v2
      - name: Build and package
        run: |
          echo BUILDVER(${{ github.ref_name }}) > src/build.version
          .\gnb.bat setup
          .\gnb.bat build MagicaLego
          .\gnb.bat package magicalego --version ${{ github.ref_name }}
        shell: cmd
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.make-release.outputs.uploadurl }}
          asset_path: ./MagicaLego_win64_${{ github.ref_name }}.zip
          asset_name: MagicaLego_win64_${{ github.ref_name }}.zip
          asset_content_type: application/zip
