name: Release MagicaLego

on:
  push:
    tags:
      - 'm*'

jobs:
  make-release:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

  windows-build:
    needs: make-release
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v6
        with:
          go-version: '1.23.x'
      - uses: microsoft/setup-msbuild@v3
      - name: Build and package
        run: |
          echo BUILDVER(${{ github.ref_name }}) > src/build.version
          .\gnb.bat setup
          .\gnb.bat build MagicaLego
          .\gnb.bat package magicalego --version ${{ github.ref_name }}
        shell: cmd
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: ./MagicaLego_win64_${{ github.ref_name }}.zip
