name: Release NextRenderer

on:
  push:
    tags:
      - 'v*'

jobs:
  make-release:
    runs-on: ubuntu-22.04
    outputs:
      uploadurl: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v4
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  android-build:
    needs: make-release
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
      - name: Build Android
        run: |
          echo "BUILDVER(${{ github.ref_name }})" > src/build.version
          ./gnb.sh setup --skip-paks
          ./gnb.sh android release
          zip -r gknextrenderer_android_${{ github.ref_name }}.zip ./android/app/build/outputs/apk/release/app-release.apk ./deploy_android.bat
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.make-release.outputs.uploadurl }}
          asset_path: ./gknextrenderer_android_${{ github.ref_name }}.zip
          asset_name: gknextrenderer_android_${{ github.ref_name }}.zip
          asset_content_type: application/zip

  linux-build:
    needs: make-release
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install autoconf autoconf-archive automake libtool curl unzip tar libxi-dev libxinerama-dev libxcursor-dev libxrandr-dev wayland-protocols libxkbcommon-dev xorg-dev ninja-build
      - name: Build and package
        run: |
          echo "BUILDVER(${{ github.ref_name }})" > src/build.version
          ./gnb.sh setup
          ./gnb.sh build
          ./gnb.sh package linux --version ${{ github.ref_name }}
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.make-release.outputs.uploadurl }}
          asset_path: ./gknextrenderer_linux64_${{ github.ref_name }}.zip
          asset_name: gknextrenderer_linux64_${{ github.ref_name }}.zip
          asset_content_type: application/zip

  windows-build:
    needs: make-release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
      - uses: microsoft/setup-msbuild@v2
      - name: Build and package
        run: |
          echo BUILDVER(${{ github.ref_name }}) > src/build.version
          .\gnb.bat setup
          .\gnb.bat build
          .\gnb.bat package windows --version ${{ github.ref_name }}
        shell: cmd
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.make-release.outputs.uploadurl }}
          asset_path: ./gkNextRenderer-windows.zip
          asset_name: gknextrenderer_win64_${{ github.ref_name }}.zip
          asset_content_type: application/zip
