name: Windows CI

on:
  pull_request:
    branches: [main, dev, 'releases/**']
  push:
    branches: [main, 'releases/**']
    paths:
      - '.github/workflows/**'
      - 'src/**'
      - 'assets/shaders/**'
      - 'tools/gnb/**'
      - 'gnb.*'
      - '**/CMakeLists.txt'

jobs:
  build:
    runs-on: windows-latest
    env:
      SDK_VERSION: 1.4.313.2
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
      - name: Download Vulkan SDK
        run: Invoke-WebRequest "https://sdk.lunarg.com/sdk/download/${env:SDK_VERSION}/windows/vulkan_sdk.exe?Human=true" -OutFile vulkan_sdk.exe -v
      - name: Install Vulkan SDK
        run: .\vulkan_sdk.exe --accept-licenses --default-answer --confirm-command install
        shell: cmd
      - name: Cache key
        id: gnb
        run: echo "key=$(.\gnb.bat info --bincache-key)" >> $env:GITHUB_OUTPUT
      - uses: actions/cache/restore@v4
        id: cache-vcpkg-restore
        with:
          path: |
            .vcpkg
            .vcpkg_bincache
          key: ${{ steps.gnb.outputs.key }}
      - uses: microsoft/setup-msbuild@v2
      - name: Setup dependencies
        run: |
          set VULKAN_SDK=C:\VulkanSDK\%SDK_VERSION%
          .\gnb.bat setup
        shell: cmd
      - name: Build
        run: |
          set VULKAN_SDK=C:\VulkanSDK\%SDK_VERSION%
          .\gnb.bat build
        shell: cmd
      - uses: actions/cache/save@v4
        if: github.event_name != 'pull_request'
        with:
          path: |
            .vcpkg
            .vcpkg_bincache
          key: ${{ steps.gnb.outputs.key }}
